### ISSUE TITLE
Amount is incorrect after auth

### ISSUE THREAD

**Issue by lilyDong** [WalletConnect/WalletConnectSwiftV2#1001]
**Describe the bug**

**SDK Version**
 - Client: [Swift]
 - Version [1.6.11]

**To Reproduce**
1. open (https://react-auth-dapp.vercel.app/)
2. Click on button "walletconnect"
3. scan and auth request
4. after auth, the amount shows but is not incorrect.

**Expected behavior**
amount should be 0.00043 ETH

**Screenshots**
![image](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/9858676/385ff6e3-3177-4c37-b13a-d0ef953c9f34)

**Comment by flypaper0** [comment]
js frontend issue
