### ISSUE TITLE
how to back to dapp after sign

### ISSUE THREAD

**Issue by LeoTnT** [WalletConnect/WalletConnectSwiftV2#1017]
Hello, now my app can connect to the wallet normally, and after agreeing to connect, you can redirect to my app. However, after I perform the sign operation, I cannot redirect back to my app. What is the cause of this?

**Comment by LeoTnT** [comment]
`                    //1. request
                    try await Sign.instance.request(params: request)
                    //2. open wallet
                    DispatchQueue.main.async {
                        UIApplication.shared.open(URL(string: "metamask://")!)
                    }`

**Comment by LeoTnT** [comment]
`
//1. request 
try await Sign.instance.request(params: request) 
//2. open wallet 
DispatchQueue.main.async { UIApplication.shared.open(URL(string: "metamask://")!) }
`

**Comment by PandaZhang530** [comment]
i have the same problem too

**Comment by LeoTnT** [comment]
> I have the same problem when I sign in metamask, is it solved?

no. The problem is sporadic, but most do not return

**Comment by ldkfreetoplay** [comment]
I solved this problem in metamask, try like this：
metamask://wc?requestId=undefined&sessionTopic=0f0a8661f4636ee5f060358dbf74e6db69a91f299fa4793a4c4416b5ae9ec1fb

`sessionTopic` is the key

**Comment by LeoTnT** [comment]
> 我在metamask中解决了这个问题，尝试这样： metamask://wc?requestId=undefined&sessionTopic=0f0a8661f4636ee5f060358dbf74e6db69a91f299fa4793a4c4416b5ae9ec1fb
> 
> `sessionTopic`是关键

Very nice.  I modified it according to your method, and the logic I wanted was realized as expected. thanks, You've been a great help to me

**Comment by LeoTnT** [comment]
> I solved this problem in metamask, try like this： metamask://wc?requestId=undefined&sessionTopic=0f0a8661f4636ee5f060358dbf74e6db69a91f299fa4793a4c4416b5ae9ec1fb
> 
> `sessionTopic` is the key

Very nice. I modified it according to your method, and the logic I wanted was realized as expected. thanks, You've been a great help to me
