### ISSUE TITLE
Can't import WalletConnect

### ISSUE THREAD

**Issue by AndrewPetrov** [WalletConnect/WalletConnectSwiftV2#1033]
**Describe the bug**
Can't import WalletConnect
**SDK Version**
 - Client:  Swift
 - Version: 1.6.17

**To Reproduce**
1. Import via SPM
2. import WalletConnect
3. See error

**Expected behavior**
import WalletConnect without problems

**Screenshots**
![SCR-20230814-da3](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/72de4f41-7a22-4bd6-98ca-e6c58c5b2a9c)
![SCR-20230814-dcp](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/e536dae9-8b2f-4d47-bf62-7c662a87b1c9)
![SCR-20230814-dcv](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/2660ed99-0794-47a5-8b92-06e4f331bc75)

**Device (please complete the following information):**
- MacOS 13.5
 - XCode 14.3.1

**Additional context**

**Comment by llbartekll** [comment]
hey @AndrewPetrov, 
if you'r developing a wallet import `Web3Wallet`

**Comment by AndrewPetrov** [comment]
In this case I have an error <img width="945" alt="image" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/4dfcb65d-e952-406f-93ec-53b8dc687a97">

**Comment by llbartekll** [comment]
you can check the implementation of that class in our example

**Comment by AndrewPetrov** [comment]
Your Example app works only because the library is included in the project directly (1). I created a new empty project, add WalletConnectSwiftV2 there (2), and created a new file with all imports that your example uses. And It doesn't compile. 
![SCR-20230814-j6v](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/c7e8f564-8381-4c87-a4cd-97fa5e30ae7b)
![SCR-20230814-j7b](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/aa4c8965-6afc-48eb-91da-fb5a66819477)

**Comment by AndrewPetrov** [comment]
It's so because DefaultCryptoProvider is a part of Wallet Connect module, but we cat import it 
![SCR-20230814-jn5](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/1746733b-ece2-446a-9336-8a4722e837db)

**Comment by llbartekll** [comment]
you just need to implement those two methods:
```public protocol CryptoProvider {
    func recoverPubKey(signature: EthereumSignature, message: Data) throws -> Data
    func keccak256(_ data: Data) -> Data
}
```
and you can use any lib you like for those methods, in our example we use `web3` but you are not restricted to integrate this one

**Comment by AndrewPetrov** [comment]
> @AndrewPetrov can we close the issue?

I believe yes, thank you for your help!

**Comment by xoniq** [comment]
@AndrewPetrov 

I had the same issue, and imported the package:

```
https://github.com/Boilertalk/Web3.swift.git
```

Then in my `Swift` file I added:

```swift
import Web3
```

The `import` doesn't fail, but still get this:

![image](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/5212771/9e0ad6fd-73f7-4fdc-afa0-bcd77d01bebd)

The only thing I need (I don't know if this approach is correct) for people to connect their wallet, to get the wallet address, as a verified wallet address in their app profile. Is this perhaps overkill? Or just fine
