### ISSUE TITLE
Fallback to relay.walletconnect.org

### ISSUE THREAD

**Issue by PandaZhang530** [WalletConnect/WalletConnectSwiftV2#1038]
<img width="625" alt="image" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/140152146/af320375-2ff0-4b07-a97d-bcb53bdc764e">

**Comment by llbartekll** [comment]
can you provide more detailed description of the issue?

**Comment by AndrewPetrov** [comment]
I have the same in your Example app

**Comment by llbartekll** [comment]
did you set your projectID?

**Comment by AndrewPetrov** [comment]
Yes I did. But only `Project ID`. Maybe there are some other variables that should be changed?

**Comment by llbartekll** [comment]
but you were never able to connect to the network? or it happens sometimes?

**Comment by PandaZhang530** [comment]
i used to make it successfully, but about 2 weeks ago, i had this problem and since then this problem happens always, no matter how many times i try

**Comment by PandaZhang530** [comment]
> @AndrewPetrov @PandaZhang530
> 
> 1. Are you located in China?
> 2. The redirect is called immediately or is there some timeout?
> 3. Could you share the whole log?
>    Thanks!

Yes, I'm in china. How to open or level up wallet connect sdk's log level for verbose logs?

**Comment by PandaZhang530** [comment]
error in connection_block_invoke_2: Connection invalid
[PROPOSER] Connecting to a pairing...
🚄 [RelayClient]: Subscribing to topic: 56292ade8d859b9018e9ec1113dad4f7695ed91f8b77371ac4d6ff91aa0abe1a - 16:23:32.1560
🚄 [WebSocket] - Fallback to relay.walletconnect.org - 16:23:37.1610
webSocketNotConnected

**Comment by PandaZhang530** [comment]
> error in connection_block_invoke_2: Connection invalid [PROPOSER] Connecting to a pairing... 🚄 [RelayClient]: Subscribing to topic: 56292ade8d859b9018e9ec1113dad4f7695ed91f8b77371ac4d6ff91aa0abe1a - 16:23:32.1560 🚄 [WebSocket] - Fallback to relay.walletconnect.org - 16:23:37.1610 webSocketNotConnected

That's all i get from the console

**Comment by AndrewPetrov** [comment]
> 

No, I'm in EU. One week ago I started integrating the Wallet Connect in our app. So It never works for me.

**Comment by AndrewPetrov** [comment]
On the start of the app I see next

**Comment by AndrewPetrov** [comment]
After connecting attempt I see
```
21.228851+0100 WalletApp[75005:3563631] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x60000011e080> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2023-08-23 11:45:21.319750+0100 WalletApp[75005:3563631]   HALC_ProxyObjectMap.cpp:153    HALC_ProxyObjectMap::_CopyObjectByObjectID: failed to create the local object
2023-08-23 11:45:21.319970+0100 WalletApp[75005:3563631]      HALC_ShellDevice.cpp:2606   HALC_ShellDevice::RebuildControlList: couldn't find the control object
URI: WalletConnectURI(topic: "53004d74ed295f64dcbb0204571ee6b9459efffb257e4b230d23e6e09a5cad2a", version: "2", symKey: "64ca9391df483276620b5971ee0fa48b76fcfa2300ea57e6440f5bec7a3f8faf", relay: WalletConnectUtils.RelayProtocolOptions(protocol: "irn", data: nil))
🚄 [RelayClient]: Subscribing to topic: 53004d74ed295f64dcbb0204571ee6b9459efffb257e4b230d23e6e09a5cad2a - 11:45:26.5660
🚄 [WebSocket] - Fallback to relay.walletconnect.org - 11:45:31.5800
2023-08-23 11:45:31.593296+0100 WalletApp[75005:3559637] [SwiftUI] Publishing changes from within view updates is not allowed, this will cause undefined behavior.
```

**Comment by AndrewPetrov** [comment]
Adding `WALLETAPP_SENTRY_DSN` removes according first error, but doesn't help to connect

**Comment by qRoC** [comment]
related to #1048

**Comment by PandaZhang530** [comment]
> related to #1048

Thans, but this does not solve my problem, sad...

**Comment by AndrewPetrov** [comment]
> @AndrewPetrov do you use VPN?

No, but solution from https://github.com/WalletConnect/WalletConnectSwiftV2/issues/1048 works well for me

**Comment by PandaZhang530** [comment]
Finally, i found that the Allowed Domains were modified by other colleague, so the solution from https://github.com/WalletConnect/WalletConnectSwiftV2/issues/1048 works well for me too. Thank you all so much!!!
