### ISSUE TITLE
 Clarification on Encryption Algorithms and Apple's Compliance Requirements

### ISSUE THREAD

**Issue by ramvi** [WalletConnect/WalletConnectSwiftV2#1044]
Hello WalletConnect Team,

I hope this message finds you well. I'm currently in the process of submitting my app to the Apple App Store, and I've encountered a question regarding the encryption algorithms used by the services and libraries integrated into the app. Specifically, Apple is inquiring about the type of encryption algorithms implemented, and whether they are proprietary, standard, or both.

Since my app utilizes WalletConnect 2.0 for data transmission, I wanted to reach out and seek clarification. Based on my understanding and research, it seems that WalletConnect might employ both standard encryption algorithms and its own protocols. Can you confirm if this is accurate?

Furthermore, given that I'm using WalletConnect, would I need to complete all the associated paperwork and compliance documentation for Apple based on the encryption methods WalletConnect employs?

Your guidance on this matter would be greatly appreciated, as it will help streamline the app submission process and ensure compliance with Apple's requirements.

Thank you for your time and assistance.

Warm regards,
ramvi

**Comment by llbartekll** [comment]
We only use Apple's implementation(CryptoKit) of ChaCha20-Poly1305.
I hope this helps.

**Comment by ramvi** [comment]
@llbartekll,

Thank you so much for your response and for clarifying the encryption methods used by WalletConnect. Your information about the encryption used is very helpful.

To confirm my understanding and proceed with the app submission process, does this mean the answer is "No" to the "Export Compliance Information" question within Apple's requirements?

I appreciate your time and help with this.

Warm regards,
ramvi


![image](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/877417/6691a52d-f303-43ca-9b95-5ac93a5d0d66)

**Comment by llbartekll** [comment]
I am sorry but I am not a legal advisor :D 
but "no" always worked for me :)

**Comment by ramvi** [comment]
I understand that you're not a legal advisor, and I truly appreciate your responses to my questions. They have been extremely helpful in clarifying the situation.

Considering that every app that integrates WalletConnect will likely face these same questions when submitting to the Apple App Store, I believe that incorporating this information into the official documentation could benefit other developers as well.

Would you like me to create a pull request (PR) to add this information to the documentation? 
Thank you once again for your assistance.

Warm regards,
ramvi
