### ISSUE TITLE
Firebase crash logs, Crashed: com.walletconnect.sdk.dispatcher

### ISSUE THREAD

**Issue by SunZhiC** [WalletConnect/WalletConnectSwiftV2#1046]
**Describe the bug**
Firebase crash logs, Crashed: com.walletconnect.sdk.dispatcher

**SDK Version**
 - Client: WalletConnectSwiftV2
 - Version 1.6.14

**To Reproduce**
I don't know how to reproduce.

**Expected behavior**
No crash

**Screenshots**
No

**Device (please complete the following information):**
 - Device:  iPhone 11
 - OS: iOS 16.6.0

**Additional context**
This is Firebase crash log under `Stack trace`
```
Crashed: com.walletconnect.sdk.dispatcher
0  libswiftCore.dylib             0x373e4 _assertionFailure(_:_:file:line:flags:) + 264
1  libswift_Concurrency.dylib     0x6160 CheckedContinuation.resume(throwing:) + 472
2  WalletConnectSwiftV2           0x4c4b4 partial apply for closure #1 in closure #1 in Dispatcher.protectedSend(_:) + 92 (Dispatching.swift:92)
3  WalletConnectSwiftV2           0x49c84 closure #3 in Dispatcher.protectedSend(_:completion:) + 79 (Dispatching.swift:79)
4  Combine                        0x2fd34 Subscribers.Sink.receive(completion:) + 448
5  Combine                        0x8dc0 protocol witness for Subscriber.receive(completion:) in conformance Subscribers.Sink<A, B> + 24
6  Combine                        0x11790 Publishers.Timeout.Inner.timedOut() + 1012
7  libswiftDispatch.dylib         0xfd4 thunk for @escaping @callee_guaranteed () -> () + 36
8  libdispatch.dylib              0x3eac _dispatch_client_callout + 20
9  libdispatch.dylib              0x7330 _dispatch_continuation_pop + 504
10 libdispatch.dylib              0x1a908 _dispatch_source_invoke + 1588
11 libdispatch.dylib              0x7208 _dispatch_continuation_pop + 208
12 libdispatch.dylib              0x6998 _dispatch_async_redirect_invoke + 584
13 libdispatch.dylib              0x15944 _dispatch_root_queue_drain + 396
14 libdispatch.dylib              0x16158 _dispatch_worker_thread2 + 164
15 libsystem_pthread.dylib        0xda0 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0xb7c start_wqthread + 8
```

under `Keys`

crash_info_entry_0 | _Concurrency/CheckedContinuation.swift:187: Fatal error: SWIFT TASK CONTINUATION MISUSE: protectedSend(_:) tried to resume its continuation more than once, throwing webSocketNotConnected!
-- | --

**Comment by llbartekll** [comment]
@SunZhiC did the issue happened before v1.6.14 too? Is the crash common?

**Comment by SunZhiC** [comment]
> common

v1.6.14 is the first time Firebase caught the crash. I suspect it is not common, and we didn't encounter it during development and testing.

**Comment by llbartekll** [comment]
thank you for the info 🙏, we will look into it

**Comment by llbartekll** [comment]
hey @SunZhiC are you still experiencing the issue?

**Comment by tureck1y** [comment]
Still have this issue with WalletConnectSwiftV2 (1.8.4)

`Crashed: com.apple.NSURLSession-delegate
0  libswiftCore.dylib             0x3886c _assertionFailure(_:_:file:line:flags:) + 264
1  libswift_Concurrency.dylib     0x59a0 CheckedContinuation.resume(returning:) + 504
2  WalletConnectSwiftV2           0x4cae8 closure #1 in closure #1 in Dispatcher.protectedSend(_:) + 100 (Dispatching.swift:100)
3  WalletConnectSwiftV2           0x4d034 partial apply for closure #1 in Dispatcher.send(_:completion:) + 64 (Dispatching.swift:64)
4  Tangem                         0x121bd8 closure #1 in WebSocket.write(string:completion:) + 139 (WebSocket.swift:139)
5  Foundation                     0x39a29c thunk for @escaping @callee_guaranteed @Sendable (@guaranteed Error?) -> () + 60
6  libdispatch.dylib              0x26a8 _dispatch_call_block_and_release + 32
7  libdispatch.dylib              0x4300 _dispatch_client_callout + 20
8  libdispatch.dylib              0xb894 _dispatch_lane_serial_drain + 748
9  libdispatch.dylib              0xc3f8 _dispatch_lane_invoke + 432
10 libdispatch.dylib              0x17004 _dispatch_root_queue_drain_deferred_wlh + 288
11 libdispatch.dylib              0x16878 _dispatch_workloop_worker_thread + 404
12 libsystem_pthread.dylib        0x1964 _pthread_wqthread + 288
13 libsystem_pthread.dylib        0x1a04 start_wqthread + 8`

**Comment by llbartekll** [comment]
@tureck1y hey, do you use starscream or urlsession for the WebSocket?

**Comment by tureck1y** [comment]
> @tureck1y hey, do you use starscream or urlsession for the WebSocket?

URLSession

**Comment by llbartekll** [comment]
To me it looks like there may be an issue with your ulrsession implementation then
>Crashed: com.apple.NSURLSession-delegate

**Comment by tureck1y** [comment]
Thank you, we will check our implementation. @llbartekll what do you think about another stacktrace?

```
Crashed: com.walletconnect.sdk.dispatcher
0  libswiftCore.dylib             0x373e4 _assertionFailure(_:_:file:line:flags:) + 264
1  libswift_Concurrency.dylib     0x6160 CheckedContinuation.resume(throwing:) + 472
2  WalletConnectSwiftV2           0x4cad0 closure #1 in closure #1 in Dispatcher.protectedSend(_:) + 96 (Dispatching.swift:96)
3  WalletConnectSwiftV2           0x4c254 closure #3 in Dispatcher.protectedSend(_:completion:) + 83 (Dispatching.swift:83)
4  Combine                        0x2fd34 Subscribers.Sink.receive(completion:) + 448
5  Combine                        0x8dc0 protocol witness for Subscriber.receive(completion:) in conformance Subscribers.Sink<A, B> + 24
6  Combine                        0x11790 Publishers.Timeout.Inner.timedOut() + 1012
7  libswiftDispatch.dylib         0xfd4 thunk for @escaping @callee_guaranteed () -> () + 36
8  libdispatch.dylib              0x3eac _dispatch_client_callout + 20
9  libdispatch.dylib              0x7330 _dispatch_continuation_pop + 504
10 libdispatch.dylib              0x1a908 _dispatch_source_invoke + 1588
11 libdispatch.dylib              0x7208 _dispatch_continuation_pop + 208
12 libdispatch.dylib              0x6998 _dispatch_async_redirect_invoke + 584
13 libdispatch.dylib              0x15944 _dispatch_root_queue_drain + 396
14 libdispatch.dylib              0x16158 _dispatch_worker_thread2 + 164
15 libsystem_pthread.dylib        0xda0 _pthread_wqthread + 228
16 libsystem_pthread.dylib        0xb7c start_wqthread + 8
```
