### ISSUE TITLE
WalletConnect - Pairing timeout error

### ISSUE THREAD

**Issue by AndriiPetrovDev** [WalletConnect/WalletConnectSwiftV2#1048]
**Describe the bug**

**SDK Version**
 - Client: [Swift]
 - Version [1.16.17]

**To Reproduce**
1. Change ProjectID in Example app
2. Run Example app
3. Scan QR from https://react-app.walletconnect.com/
4. See in console `🚄 [WebSocket] - Fallback to relay.walletconnect.org `
5. There will be a alert `WalletConnect - Pairing timeout error`

**Expected behavior**
Connection without issues

**Screenshots**

https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/0a0724f8-0481-4b69-b7dc-3d6648884f17

**Device (please complete the following information):**
 - Device: [e.g. iPhone13Pro]
 - OS: [e.g. iOS16.6]

**Additional context**
Changed ProjectID in both places - Configuration.xcconfig and project build settings

**Comment by qRoC** [comment]
Starscream set `Origin`, but relay.walletconnect.com does not accept it

**Comment by ShootingGuard24** [comment]
我遇到了一个问题, 我在调用 DApp 程序(V2版本号是 : 1.6.17 )的时候, 生成的二维码无法进行正常的扫码登录链接, 跳转的目标应用告知我, 发生了一个未知的错误, 我 copy 到所生成二维码的链接也无法拿去使用(跳转其他应用也没办法成功授权), 为此我录制了操作步骤的视频, 希望能在这里得到大家的热情帮助


https://github.com/WalletConnect/WalletConnectSwiftV2/assets/48764850/3c8a8a75-e903-45b3-80b5-3c60fa0a25fe

**Comment by rkingxbank** [comment]
@ShootingGuard24  use Zerion wallet ，not use imToken wallet

**Comment by ShootingGuard24** [comment]
@rkingxbank Other wallets can be used, but the imtoken wallet cannot be linked normally. I would like to know why it cannot be used? Looking forward to your reply XD
