### ISSUE TITLE
eth_signTypedData methods in Example/ExampleApp.xcodeproj do not work

### ISSUE THREAD

**Issue by rkingxbank** [WalletConnect/WalletConnectSwiftV2#1051]
**Describe the bug**
after connect wallet, enter AccountRequestViewController. And click eth_signTypedData。popup a response viewcontroller with error message.

**SDK Version**
 - Client: [swift] dapp in ExampleApp 
 - Version [1.6.17]

**To Reproduce**
1. Open Example/ExampleApp.xcodeproj
2. Select DApp target on Xcocde top center
3. Click connect button in dapp
4. After sucessful connected a wallet
5. Click on one account
6. Click eth_signTypedData
7. Received Error eth_signTypedData

**Expected behavior**
open connected wallet, user approve. And back to ExampleApp. Dapp receive signed result.

**Screenshots**
![IMG_0480](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/94829739/588e5540-02b7-45a1-9908-3a5a5870900a)
![IMG_0481](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/94829739/54b8396b-a6ca-454d-ad2a-8f153b624a21)
![IMG_0482](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/94829739/4d6c839b-63c6-412f-b0b9-257e088e8cca)

**Device (please complete the following information):**
 - Device: [iPhone12]
 - OS: [iOS16.5.1]

**Additional context**

**Comment by flypaper0** [comment]
We're updated our sample dapp, could you try to reproduce again please?
