### ISSUE TITLE
Shared instance access Fatal error

### ISSUE THREAD

**Issue by jl3000** [WalletConnect/WalletConnectSwiftV2#1061]
**Describe the bug**
When attempting to authorize a connection to a wallet (Trust Wallet) while debugging the demo DApp in tethered mode, an error is encountered. The error occurs right after authorizing the connection on the wallet app while the demo DApp is presented again.

The issue only occurs in tethered mode.

Error : WalletConnectSync/Sync.swift:12: Fatal error: Error - you must call Sync.configure(_:) before accessing the shared instance.

**SDK Version**
 - Client: [Swift]
 - Version [1.7.0]

**To Reproduce**
1. Build and run the demo DApp in tethered mode using Xcode 14.3.1.
2. Connect to Trust Wallet and authorize the connection when prompted.
3. Observe the error message mentioned above.

**Expected behavior**
The demo DApp should be able to authorize the connection to Trust Wallet and proceed without encountering the fatal error. 

**Device (please complete the following information):**
 - Device: [11 Pro]
 - OS: [16.6]

**Comment by flypaper0** [comment]
We're updated sample dapp. Try again please
