### ISSUE TITLE
No such module 'Web3Wallet'

### ISSUE THREAD

**Issue by MarcoDotIO** [WalletConnect/WalletConnectSwiftV2#1129]
**Describe the bug**
The main issue is that, despite tests and example being able to import this module, my own project that has imported the WalletConnectSwiftV2 package isn't able to import this package.

**SDK Version**
 - Client: Swift
 - Version 5.9

**To Reproduce**
1. Set up a new iOS SwiftUI project
2. Import the WalletConnectSwiftV2 Package, with the version being 1.6.4
3. Import `Web3Wallet`

**Expected behavior**
That I can be able to import Web3Wallet and use WalletConnectModal in my project.

**Screenshots**
![Screenshot 2023-09-20 at 4 52 59 PM](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/20867620/855198f5-0e4a-457f-8117-b5baa8c05685)

**Device (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: 17.0 RC
 - Browser N/A
 - Version N/A

**Additional context**
Xcode version is Version 15.0 beta 8 (15A5229m)

**Comment by MarcoDotIO** [comment]
Update: Figured out that I needed to add the package in the frameworks section, under the project target. Closing this issue.

![Screenshot 2023-09-20 at 4 59 14 PM](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/20867620/da51aba3-d4b5-49dd-82e5-70ff9025d650)

**Comment by MarcoDotIO** [comment]
![Screenshot 2023-09-20 at 5 01 17 PM](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/20867620/f4e476ef-66db-4146-9f84-4854ec998886)

Actually never mind, reopening this issue. Don't know if this issue exists within future versions or not (further context, yes this issue exists with the recent version).

**Comment by flypaper0** [comment]
> ![Screenshot 2023-09-20 at 5 01 17 PM](https://private-user-images.githubusercontent.com/20867620/269418096-f4e476ef-66db-4146-9f84-4854ec998886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTY4NjAsIm5iZiI6MTcwMjkxNjU2MCwicGF0aCI6Ii8yMDg2NzYyMC8yNjk0MTgwOTYtZjRlNDc2ZWYtNjZkYi00MTQ2LTlmODQtNDg1NGVjOTk4ODg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE2MjI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYzJmZDBiYjRiNWVlZTI0YmJiODA3NTZjMWVhODI0OTA3ZjQ3OTU4ZGQ5OWNhNTk1NWJhYzNmNGY0NTM3MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U4yZgSsKXc-FF7Y3jQJTuLmVyXy09NdmsdYWQ9dhcBU)
> 
> Actually never mind, reopening this issue. Don't know if this issue exists within future versions or not (further context, yes this issue exists with the recent version).

web3modal not the part of this package anymore. As WalletConnectModal is deprecated try to use Web3Modal separately. https://github.com/WalletConnect/web3modal-swift
