### ISSUE TITLE
iOS 17 bridge server connection error

### ISSUE THREAD

**Issue by AndreyMaksimkin** [WalletConnect/WalletConnectSwiftV2#1136]
**Describe the bug**
iOS 17 Connection error

**SDK Version**
 - Client: 1.8.4

**To Reproduce**
We faced with a problem on a client with iOS 17. We cannot connect to the bridge server. The error is 

UserInfo={NSErrorFailingURLStringKey=https://relay.walletconnect.com/websocket?vsn=2.0.0, NSErrorFailingURLKey=https://relay.walletconnect.com/websocket?vsn=2.0.0, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalWebSocketTask <883725ED-6B65-4712-B6A2-39F55D27354F>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalWebSocketTask <883725ED-6B65-4712-B6A2-39F55D27354F>.<1>, NSLocalizedDescription=The request timed out.}

Maybe we need to use Apple Transport Security or something like that?

**Comment by AndreyMaksimkin** [comment]
@flypaper0 could you help me?

**Comment by llbartekll** [comment]
hey @AndreyMaksimkin do you use Starscream or your own socket implementation?

**Comment by AndreyMaksimkin** [comment]
Looks like it was fixed somehow. Thank you guys!
