### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by chrismaddern** [WalletConnect/WalletConnectSwiftV2#1229]
Is it your intention to follow [semver](https://semver.org/) on WalletConnectSwiftV2?

We allow updates on same major version for trusted dependencies and this has caused breaking changes for us twice.

Most recently, the addition of Redirect to AppMetadata — an optional field, but required in the initializer. This causes the change to be breaking to all(?) integrators instantiating the `AppMetadata` class.

For now, I'm pinning WalletConnect and preventing updates.

**Comment by llbartekll** [comment]
hey @chrismaddern yes this is our intention and my apologies if sometime it fails.
