### ISSUE TITLE
error: VerifyContext has a problem

### ISSUE THREAD

**Issue by xwal** [WalletConnect/WalletConnectSwiftV2#1233]
**Describe the bug**
The isScam is false, but the VerifyContext will be .scam.
<img width="1174" alt="image" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/1863204/2ff3aa96-2c65-4f3d-bc15-7806a31a8017">

**SDK Version**
 - Client: Swift
 - Version 1.9.8

**To Reproduce**
1. Go to https://pancakeswap.finance
2. Click on 'Connect Wallet'

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

**Comment by xwal** [comment]
should change `guard isScam == nil else {` to `guard isScam ?? false else {`

**Comment by xwal** [comment]
And I scan opensea.io and https://uniswap.org/ always show .unknown. and the api https://verify.walletconnect.com/attestation/267c86f8624562d268a5ddb29ec439f7f05b84e0a03c216490cff10d5cb61d2c is always 404.

**Comment by llbartekll** [comment]
hey @xwal, please upgrade to 1.9.9

**Comment by wongzigii** [comment]
I have the same issue. 
 response from https://api.blowfish.xyz/v0/domains
  {
    "domain": "uniswap.org",
    "status": "PROCESSED",
    "riskScore": 0.0,
    "labels": [
      "source=blowfish_whitelist",
      "source=brand_whitelist",
      "source=defi_llama_whitelist"
    ],
    "warnings": []
  },

Why the verifyContext still showing unknown? @llbartekll

**Comment by llbartekll** [comment]
@wongzigii did you upgrade to 1.9.9?

**Comment by wongzigii** [comment]
> @wongzigii did you upgrade to 1.9.9?

I can't upgrade to 1.9.9. When I upgrade to 1.9.9, the connection failed.

> pairClientWeb socket is not connected to any URL.

**Comment by wongzigii** [comment]
> And I scan opensea.io and https://uniswap.org/ always show .unknown. and the api https://verify.walletconnect.com/attestation/267c86f8624562d268a5ddb29ec439f7f05b84e0a03c216490cff10d5cb61d2c is always 404.

I have the same problem. Did you upgrade to 1.9.9 finally?

**Comment by xwal** [comment]
Yes, I have upgraded.

> > And I scan opensea.io and https://uniswap.org/ always show .unknown. and the api https://verify.walletconnect.com/attestation/267c86f8624562d268a5ddb29ec439f7f05b84e0a03c216490cff10d5cb61d2c is always 404.
> 
> I have the same problem. Did you upgrade to 1.9.9 finally? @xwal I am not sure is this releated to the domain pollution. #1009

**Comment by xwal** [comment]
And for unknown case, I have ignored it. Some wallets e.g. Rainbow ignore the "Unverified" state - up to you @wongzigii
