### ISSUE TITLE
WalletConnectURI(deeplinkUri: URL) doesn't take into account percent encoding

### ISSUE THREAD

**Issue by simonmcl** [WalletConnect/WalletConnectSwiftV2#1248]
**Describe the bug**
`WalletConnectURI(deeplinkUri: URL)` will return nil if its percent encoded. The constructor only checks for "wc:". if the colon is percent encoded, the check fails and it returns nil

**SDK Version**
 - Client: Swift
 - Version 1.9.9

**To Reproduce**
Try to use a percent encoded URL

**Expected behavior**
SDK should check if its percent encoded and handle the situation if so

**Comment by flypaper0** [comment]
What is the use case? Where are you getting percent encoded string?

**Comment by simonmcl** [comment]
@flypaper0 a web based dApp sent it to my app like that. I assume some frontend framework/library/utility etc is doing this automatically. Likely to happen in the wild with some many technologies around

**Comment by llbartekll** [comment]
will be included in the next release
