### ISSUE TITLE
Auth token error upgrading from 1.9.9 -> 1.10.0

### ISSUE THREAD

**Issue by simonmcl** [WalletConnect/WalletConnectSwiftV2#1264]
**Describe the bug**
After migrating to 1.10.0 the socket fails to connect and the console is filled with:

![Screenshot 2023-12-20 at 14 18 58](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/8058386/5a1c3fe3-c309-412c-b795-047f0f55f0c1)

After debugging it seems that setting up an App Group is now required? and required to be passed into `Networking.configure(groupIdentifier: "", projectId:....` . If this isn't done it fails to connect. Why is this now required? Its also not explained or detailed in the project repo

Also note many of the links in the README are broken

Semi-unrelated. I've noticed that 1.10 adds a `pairingDeletePublisher` i've been waiting for this to help diagnose an issue. But i'm confused how to access it? Its not available on `Pair.instance` and `Sign.instance.pairingClient.pairingDeletePublisher` returns an error due to `pairingClient` being private. How do I access this?

**SDK Version**
 - Client: Swift
 - Version: 1.10.0

**Comment by vehicles4real** [comment]
Saya my ledger on Google drive got corrupt it always happens when I've got trillions on it. Please assist

**Comment by llbartekll** [comment]
hey @simonmcl the App Group is now required because we have released an upgraded Push sdk, keys and some session data now needs to be shared with UNNotificationServiceExtension.
> But i'm confused how to access it? Its not available on Pair.instance

We will fix this in the next release but notice that Web3WalletClient exposes this publisher already

**Comment by SunZhiC** [comment]
I still meet this error in 1.8.4, can I use the SDK without an entitlement? I don't need this feature.
