### ISSUE TITLE
WalletConnect Library Fails Silently with Outdated QR Codes

### ISSUE THREAD

**Issue by light-cloud** [WalletConnect/WalletConnectSwiftV2#1276]
**Describe the bug**
The WalletConnect library stops functioning without any error notification when an outdated QR code is scanned. This issue leads to a lack of feedback for the user, making it unclear that the QR code is no longer valid.

**SDK Version**
 - Client: Swift
 - Version 1.9.9

**To Reproduce**
1. Generate a QR code for connection.
2. Photograph the QR code.
3. Scan the QR code with a second device and decline the connection.
4. Attempt to scan the same QR code with the first device. No response is observed. The `Pair.instance.pair(uri: uri)` function does not trigger any error in the latest SDK version, leaving no option to handle this scenario or display an alert indicating the QR code's invalidity.

**Expected behavior**
An error should be triggered to inform about the invalid or outdated QR code, enhancing user awareness and experience.

**Comment by llbartekll** [comment]
once pairingUri/QR code expires it should be dismissed and not presented to the user anymore.

**Comment by llbartekll** [comment]
hey @light-cloud, the most recent release introduces pairing expiry param in the URI. Tho to execute the logic both a dapp and a wallet need to be on the last version.
