### ISSUE TITLE
Unable to redirect back to dApp after connecting wallet (Trust/MetaMask) in iOS 17

### ISSUE THREAD

**Issue by AakifNadeem** [WalletConnect/WalletConnectSwiftV2#1303]
**Describe the bug**
Tried connecting the wallet from dApp using Web3Modal and after redirecting to wallet (Trust/MetaMask) and connecting it I am unable to redirect back to DApp.

**SDK Version**
 - Client: [Xcode 15.1]
 - Version [1.12.0]

**Expected behavior**
Redirect back to Dapp after accepting connection from wallet in iOS 17 same as it does for iOS 16. 

**Device (please complete the following information):**
 - Device: [iPhone 12 ]
 - OS: [iOS 17.3]

**Comment by SunZhiC** [comment]
In the end, Apple disabled this private method.
