### ISSUE TITLE
Apple's Privacy Manifest requirements

### ISSUE THREAD

**Issue by Foboz** [WalletConnect/WalletConnectSwiftV2#1319]
**Describe the bug**
Please add `.xcprivacy` Privacy Manifest.

There's a new Apple requirement regarding data and APIs usage:
https://developer.apple.com/news/?id=3d8a9yyh

- Starting March 13: It's optional, and App Store Connect will generate an email if `.xcprivacy` is missing.
- Starting May 1: It's required, and app updates will likely be rejected.

**SDK Version**
 - Client: Swift

**Additional context**
Links:
- [Apple update (12/7/2023)](https://developer.apple.com/news/?id=r1henawx)
- [Apple update (29/2/2024)](https://developer.apple.com/news/?id=3d8a9yyh)
- [Privacy manifest files](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)
- [Describing data use in privacy manifests](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)

**Comment by SunZhiC** [comment]
@llbartekll Sir, can you publish a new pod version with PrivacyInfo?

**Comment by llbartekll** [comment]
@SunZhiC it's been added here https://github.com/WalletConnect/WalletConnectSwiftV2/pull/1331

**Comment by SunZhiC** [comment]
> @SunZhiC it's been added here #1331

Got it, thank you.

**Comment by llbartekll** [comment]
closing this one, if there are any issues we can reopen.
