### ISSUE TITLE
WalletConnect 100% CPU usage and increased device temperature due to the checkPairingState being run each second

### ISSUE THREAD

**Issue by chichkanov** [WalletConnect/WalletConnectSwiftV2#1330]
**Describe the bug**
Hello WC team!
We experience a huge CPU usage and highly increase device temperatures while using your SDK. 
We use WalletConnect Swift Web3Modal, but according to the logs the issue is in the main WC Swift V2 library.
From what I've found you setup a timer in PairingStateProvider which updates each second and inside it Decodes the sessions from the storage.

**SDK Version**
 - Client: Swift
 - Version: 1.13.0

**To Reproduce**
1. Initialize WC SDK
2. Open Xcode App profiler and check CPU usage

**Expected behavior**
No high CPU usage. 
1. If it is essential to check session each second, at least cache them in-memory to avoid long running operations.
2. Moreover, some of these operations are happening on the main thread, which also affects an app performance

**Screenshots**
Attaching the place where the issues is located

<img width="820" alt="Screenshot 2024-03-21 at 2 57 32 PM" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/22872688/f685d02b-839e-46b9-a62d-e9744a710fd7">

**Device (please complete the following information):**
 - Device: iphone 15 pro max
 - OS: ios 17.4
 - Browser - (native app)

**Comment by llbartekll** [comment]
thanks for reporting this, I will investigate.

**Comment by alexanderkhitev** [comment]
Hello guys! Do you have any news/updates? Thanks!

**Comment by llbartekll** [comment]
Hey, yes, we expire pairings earlier now and there should not be as many objects in the storage anymore. 
Please upgrade to the latest version

**Comment by alexanderkhitev** [comment]
> Hey, yes, we expire pairings earlier now and there should not be as many objects in the storage anymore. Please upgrade to the latest version

Hey! Ok, thank you!

**Comment by llbartekll** [comment]
thanks for confirming, closing the issue then
