### ISSUE TITLE
Web3Wallet.instance.authenticateRequestPublisher not firing

### ISSUE THREAD

**Issue by arturdev** [WalletConnect/WalletConnectSwiftV2#1338]
**Describe the bug**
With the deprecation of `Auth.instance.authRequestPublisher` in favor of `Web3Wallet.instance.authenticateRequestPublisher`, the auth (SignIn) mechanism got broken.
Taking an example from [web-examples](https://github.com/WalletConnect/web-examples): https://react-auth-dapp.walletconnect.com/
After scanning the QR Code, and calling `Web3Wallet.instance.pair(uri: wcURI)`, the event `Web3Wallet.instance.authenticateRequestPublisher` never gets sent.

My observations are the following: 
After pairing, the `requestPublisher` of  `NetworkingInteractor` gets triggered (which is good), where `request.method` is `wc_authRequest`, but the filtration logic always fails (the highlighted line), because `requestSubscription` method never gets called with `AuthRequestProtocolMethod` prior pairing. It does with `SessionAuthenticatedProtocolMethod` (aka `"wc_sessionAuthenticate"`) but never with `AuthRequestProtocolMethod`, which leads to `Web3Wallet.instance.authenticateRequestPublisher` not functioning.

<img width="1192" alt="image" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/6263856/af7e96e8-cc26-4735-9cd3-82a9ab044492">

**SDK Version**
 - Client: Swift
 - Version 1.18.4

**To Reproduce**
1. Go to https://react-auth-dapp.walletconnect.com/
2. Click on WalletConnect
3. Scan the QR from a Wallet app utilizing the latest version of WalletConnectSwiftV2.
4. `Web3Wallet.instance.authenticateRequestPublisher` never gets triggered.

**Expected behavior**
After pairing the scanned uri, the `Web3Wallet.instance.authenticateRequestPublisher` should be fired (according to docs). 
I believe, if `Auth` is deprecated, the library should automatically fallback the `wc_authRequest` to `wc_sessionAuthenticate`. Or otherwise, provide a way to handle `wc_authRequest`s.

**Device (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS 17.3.1

**Comment by llbartekll** [comment]
hello @arturdev `wc_authRequest` and `wc_sessionAuthenticate` are not compatible and authenticateRequestPublisher will publish only on `wc_sessionAuthenticate`. you can test it against https://web3modal-laboratory-git-feat-sign-25-walletconnect1.vercel.app/library/ethers-siwe/.

tho `Auth.instance.authRequestPublisher` will still work for wc_authRequest

to learn more about 1-click auth take a look at our docs https://docs.walletconnect.com/web3wallet/authenticatedSessions

**Comment by arturdev** [comment]
Hi @llbartekll
Thanks for the reply.
I know that with `Auth.instance.authRequestPublisher` it will work.. the thing is that it is already DEPRECATED in favour of `Web3Wallet.instance.authenticateRequestPublisher`! However, it seems it is not true...
So what is the real usage of `Web3Wallet.instance.authenticateRequestPublisher` and how to support the authentication with this new version?

**Comment by llbartekll** [comment]
> So what is the real usage of Web3Wallet.instance.authenticateRequestPublisher and how to support the authentication with this new version?

please take a look into our docs https://docs.walletconnect.com/web3wallet/authenticatedSessions

>he thing is that it is already DEPRECATED in favour of Web3Wallet.instance.authenticateRequestPublisher! However, it seems it is not true...

what do you mean it's not true? those are different protocol methods

**Comment by arturdev** [comment]
@llbartekll is there any example dapp for the new auth protocol testing? 
https://react-auth-dapp.walletconnect.com/
This one still uses the old one, which is deprecated according to your docs.

**Comment by llbartekll** [comment]
also check this https://docs.walletconnect.com/web3wallet/authenticatedSessions#testing-one-click-auth

**Comment by arturdev** [comment]
@llbartekll  The mentioned website: https://react-dapp-v2-c62i0q6mr-walletconnect1.vercel.app/
I can see only "Connect" option, and not one-click-auth... 
Am I wrong?

**Comment by llbartekll** [comment]
That’s fine, you will connect and authenticate in a single step.
