### ISSUE TITLE
1.20+ no longer returns any Pairings

### ISSUE THREAD

**Issue by simonmcl** [WalletConnect/WalletConnectSwiftV2#1420]
**Describe the bug**
I'm trying to push a bug fix for my app, but apple is complaining that the privacy manifests for wc2 in 1.19.3 are invalid. I've updated to 1.20.3 but its broken a sizable portion of my app. My app displays a list of "Connected Apps" allowing users to disconnect or switch account by touching them. This is done by fetching the pairings via `Pair.instance.getPairings()`, and then later by finding the active session for each one via the `pairingTopic` (which is now deprecated?). As of 1.20+, fetching the list of pairings always returns an empty array. I've tried looking at quickly changing to display sessions instead, but these don't have a function to disconnect

I'm not sure if this is a bug, or something thats missing a migration guide. I'm on a VERY tight deadline atm. I'd really appreciate if someone could help me asap

**SDK Version**
 - Client: Swift
 - Version: 1.20

**To Reproduce**
1. Connect to a dApp
2. Query pairings via Pair.instance.getPairings()

**Expected behavior**
Pairings should be returned

**Comment by simonmcl** [comment]
@llbartekll are you available to look at this please?

**Comment by llbartekll** [comment]
hey @simonmcl 
we have deprecated pairings because no dapps were using them to propose new sessions as it was initially intended. For your problem I would suggest to display sessions instead as you wanted to do.

> I've tried looking at quickly changing to display sessions instead, but these don't have a function to disconnect

They have a disconnect() method, Web3Wallet.instance.disconnect(topic:)

**Comment by simonmcl** [comment]
@llbartekll 
> no dapps were using them to propose new sessions as it was initially intended

If I understand correctly, that is what we are doing in Tezos. We are allowing user to "Switch account", which proposes a new session on the same Pairing, with a different wallet address, allowing users to interact with a different wallet without having to disconnect/reconnect. Has all of this been removed?

**Comment by simonmcl** [comment]
@llbartekll 

Web3Wallet isn't being found, and can't find it via import either, is there extra setup needed when using SPM?

![Screenshot 2024-09-27 at 10 06 55](https://github.com/user-attachments/assets/91b2334c-184e-4888-8c86-639f640da383)

**Comment by llbartekll** [comment]
can I try this user experience somewhere?

**Comment by llbartekll** [comment]
> Web3Wallet isn't being found

it's in the same package

**Comment by simonmcl** [comment]
@llbartekll You can download the testflight via: https://x.com/KukaiWallet/status/1788910754399158439

and either try it with OBJKT.com or mooncakes.fun  heres a demo video: https://x.com/simon_mcl/status/1802713950682812916


> it's in the same package

Can't be found in code, can't be found via import and you can see I have `WalletConnectSign` imported so the package is there
![Screenshot 2024-09-27 at 10 10 48](https://github.com/user-attachments/assets/88561ba7-63bd-48f6-8e1e-0f72e273d76c)

**Comment by llbartekll** [comment]
I would guess it's some xcode issue 🤔 but you should be able to disconnect a session with Sign.instance.disconnect() too.

> We are allowing user to "Switch account", which proposes a new session on the same Pairing,

could you just accept a session from the wallet with multiple accounts included?

**Comment by simonmcl** [comment]
@llbartekll 

> could you just accept a session from the wallet with multiple accounts included?

Maybe we could, but thats not how the ecosystem has been setup to work right now. The current functionality is now in all our dApps. We'd likely have to get them all to change their UI to display multiple wallet addresses, embark on a migration, etc. This is a massive task

short term, we have been fighting an apple rejection for ~2 months. It just got approved. But during that 2 months we found a bug. If we resubmitted we'd have to go to square one with the review. So we decided to silently push it with the intention to immediately push a bug fix. In that time the privacy manifest stuff seems to have changed. Is there any possibility I could get a version of 1.19.3 with the privacy manifest changes so that I can unblock this for now

medium term, what is the possibility of getting pairings undeprecated since we were planning to use it quite heavily? Someone else also seems to be put out by this change, possible also doing something similar: https://github.com/orgs/WalletConnect/discussions/5390

**Comment by llbartekll** [comment]
> Is there any possibility I could get a version of 1.19.3 with the privacy manifest changes so that I can unblock this for now

I think for a quick fix, you could fork the repo and cherry pick this commits on 1.19.3:
https://github.com/WalletConnect/WalletConnectSwiftV2/pull/1414/commits/a2936af3587d25d1aeeb1da1b68199d508025531
https://github.com/WalletConnect/WalletConnectSwiftV2/pull/1416/commits/40a161e31ccf1ab4bfb6ac878c4eb5583964d7e5

I will think what else we can do

**Comment by simonmcl** [comment]
@llbartekll ok i've done that and looks to have worked, thanks. Will test and push it later

FYI it looks like you have to manually include `Web3Wallet` in xcode under "Frameworks, Libraries, and Embedded Content", otherwise it can't be used. Should either include that in a setup instruction or ideally see if the SPM package can be updated to make it automatic somehow

Re: Pairing. You mentioned that "no dApp was using this". Was this discussed somewhere? Was there a request for feedback in some dev channel? This pairing / switch wallet feature is something we were going to build upon quite heavily in the future, as Tezos is embarking on a massive change at the minute (e.g. bringing in EVM compatible enshrined rollups). This feature is part of our plans. We'd be keen to make sure it doesn't get dropped, or an equivalent is found. Want to make sure were not missing critical info like this
