### ISSUE TITLE
ITMS-91108: Invalid privacy manifest in 1.20.3

### ISSUE THREAD

**Issue by ngn999** [WalletConnect/WalletConnectSwiftV2#1423]
**Describe the bug**

**SDK Version**
 - Client: [e.g.  Swift]
 - Version 1.20.3

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

> ITMS-91108: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “WalletConnect_WalletConnectModal.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk.

**Comment by Priya0nka** [comment]
I have got related issue

ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “WalletConnect_WalletConnectRelay.bundle/PrivacyInfo.xcprivacy”. Keys and values in your app’s privacy manifests must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by llbartekll** [comment]
hey @ngn999 are you using WalletConnectModal?

**Comment by ngn999** [comment]
> hey @ngn999 are you using WalletConnectModal?

Yes.

**Comment by llbartekll** [comment]
Ok, we are no longer supporting it, so I would recommend you to fork this repo and add PrivacyInfo manifest file in the same way it's added for every other package.
here you have a reference: https://github.com/WalletConnect/WalletConnectSwiftV2/pull/1414/files
