### ISSUE TITLE
Move project IDs to config file, add to gitignore 

### ISSUE THREAD

**Issue by MisterVants** [WalletConnect/WalletConnectSwiftV2#145]
Project IDs should be placed on a .xcconfig file to avoid overflowing the test environment on a single project.

**Comment by chadyj** [comment]
Another option we discussed. Using Github Secrets.

**Comment by flypaper0** [comment]
> Another option we discussed. Using Github Secrets.

+ 1 for Github Secrets

**Comment by flypaper0** [comment]
closed with https://github.com/WalletConnect/WalletConnectSwiftV2/pull/519
