### ISSUE TITLE
Validate minimum required Namespace parameters after update

### ISSUE THREAD

**Issue by flypaper0** [WalletConnect/WalletConnectSwiftV2#227]
**Is your feature request related to a problem? Please describe.**

SDK allow to pass empty Dictionary as namespaces parameter. 

**Describe the solution you'd like**
I suppose we need to check: 
- `[String: SessionNamespace]` not empty
- `SessionNamespace` has one or more accounts

**Comment by llbartekll** [comment]
or is a "superset" of proposed namespaces as proposed namespaces are considered minimal requirements

**Comment by MisterVants** [comment]
> or is a "superset" of proposed namespaces as proposed namespaces are considered minimal requirements

Aren't this being checked already, with the validations?

**Comment by flypaper0** [comment]
> > or is a "superset" of proposed namespaces as proposed namespaces are considered minimal requirements
> 
> Aren't this being checked already, with the validations?

You couldn't delete last account for chain, but it's possible to delete all chains from [String: Namespace] map

**Comment by MisterVants** [comment]
Empty namespace update case already covered in `testUpdateLessThanRequiredChains`
