### ISSUE TITLE
Fix potential crash on malformed QR code scan

### ISSUE THREAD

**Issue by MisterVants** [WalletConnect/WalletConnectSwiftV2#248]
**Describe the bug**
`PairEngine` FIXME tag.

**Expected behavior**
The SDK must not crash when scanning a malformed QR code.

**Comment by MisterVants** [comment]
Not as serious as I thought, the failure case doesn't crash. Still worth taking a look.

**Comment by llbartekll** [comment]
remove force unwraps from pair method
