### ISSUE TITLE
Migrate example apps views to use SwiftUI

### ISSUE THREAD

**Issue by MisterVants** [WalletConnect/WalletConnectSwiftV2#251]
The example app's views should be migrated to layout using SwiftUI. The navigation should continue to use view controllers – `UIHostingController` subclasses – while all layout is done in SwiftUI views.

Here's a checklist for migrating the app screens to use SwiftUI, just open a separate issue when working on one of these:

Wallet:
- [ ] Migrate WalletView screen.
- [ ] Migrate RequestView screen.
- [ ] Add preview to SessionDetailView.

Dapp:
- [ ] Migrate SelectChainView.
- [ ] Migrate ConnectView.
- [ ] Migrate AccountRequestView.
- [ ] Migrate AccountsView.
- [ ] Migrate ResponseViewController.
- [ ] Redesign navigation and UX.

**Comment by zkhalapyan** [comment]
This has been an interesting question for me — most companies still use UIKit since SwiftUI is still not fully production ready; is it worth to stick to UIKit for now>?
