### ISSUE TITLE
Unify JSON-RPC request & response API

### ISSUE THREAD

**Issue by MisterVants** [WalletConnect/WalletConnectSwiftV2#256]
Right now, there are multiple types in the project that represent the same schema of a JSON-RPC request or response (`WCRequest`, `JSONRPCRequest`, `ChatRequest`, etc). They are basically duplicates that offer the same functionality, but increase the complexity of the codebase and the effort for maintaining them.

The goal is to provide a unified JSON-RPC request/response pattern API, that: 
- Is agnostic of any WalletConnect domain rules;
- Is as compliant as possible with the [JSON-RPC 2.0 specs](https://www.jsonrpc.org/specification);
- Can replace the current JSON-RPC types scattered around the project.

This aims to reduce the complexity of the codebase and increase the scalability of the project.

The solution can be provided in its own swift package (`import JSONRPC`) and tested in isolation.

**Comment by Mike117687** [comment]
merge-these-changes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
