### ISSUE TITLE
Add client id for v2 broker support

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/WalletConnectSwiftV2#263]
Add client id for v2 broker support

More context https://github.com/WalletConnect/walletconnect-specs/issues/60

- [x] #284
- [x] #285
- [x] #286
- [x] #287
- [x] #292
- [x] #288
- [x] #289
- [x] #290
- [x] #291

**Comment by chadyj** [comment]
Challenge: https://gist.github.com/pedrouid/a09452a25b0dbf90ee269601874554a7

**Comment by llbartekll** [comment]
- [ ] - JWT
- [ ] - JWT Signer
- [ ] - JWT Encoder
- [ ] - SocketAuthenticator
- [ ] - ED25519DIDKeyFactory
- [ ] - ClientIdStorage
- [ ] - AuthChallengeProviding
- [ ] - Add Bearer to Web socket request
