### ISSUE TITLE
Got error on webSocketNotConnected after scan an QR code

### ISSUE THREAD

**Issue by lmcmz** [WalletConnect/WalletConnectSwiftV2#278]
**Describe the bug**
For now, the example app is not working when scanning the QR code.

**SDK Version**
 - Client: Swift
 - Version: `v0.7.0-beta.101`

**To Reproduce**
1. Go to https://react-app.walletconnect.com
2. Click on connect
3. Open example wallet App
4. Scan the QR code
5. Error shown

**Expected behavior**
Wallet connect should establish the connection.

**Screenshots**
![Screen Shot 2022-06-18 at 10 59 49 pm](https://user-images.githubusercontent.com/9669733/174439640-24a06631-e76b-4e11-8102-1b496e25cfe5.png)

**Device (please complete the following information):**
 - Device: iPhone12Pro Max
 - OS: iOS15
 - Browser: Chrome

**Comment by bcosma** [comment]
For me, this was fixed in v0.8.1-beta.102

**Comment by llbartekll** [comment]
@Imcmz still an issue?

**Comment by llbartekll** [comment]
I was able to reproduce the error only with a debugger connected and activated breakpoint for >~30. Web socket disconnects in abnormal conditions and there is not trigger to connect it back. It may be inconvenient during debugging but won't cause any issues after app release. 
If anyone can notice that behaviour without activating breakpoint please let us know so we can examine the issue closer.

**Comment by lmcmz** [comment]
Let me update my local version and re-test it. Thanks

**Comment by lmcmz** [comment]
Tried the latest code, and it works fine. :)
Close it accordingly

**Comment by lmcmz** [comment]
Encountered this issues again recently, hence reopen it. It happens intermittently.

**Comment by llbartekll** [comment]
@lmcmz is it possible that it was caused by the breakpoint?

**Comment by lmcmz** [comment]
Ahh, yes.  That's good point !! 
It does happens when I put breakpoint in Xcode. 
Let me close it then, if I encountered other scenario will update here again.
Thanks, @llbartekll
