### ISSUE TITLE
WalletConnectClientDelegate's Session object is ambiguous and conflicts with another Session object

### ISSUE THREAD

**Issue by zkhalapyan** [WalletConnect/WalletConnectSwiftV2#319]
Have a class that tries to conform to `WalletConnectClientDelegate`, you'll encounter an issue where the object `Session` is ambiguously defined. Seems like it's conflicting with an object definition in V1 which is getting merged into V2. 🤷‍♂️

```

import WalletConnectSwift
import WalletConnect
...

extension AppDelegate: WalletConnectClientDelegate {
    ...
    func didSettle(session: Session){}
   ...
}

```

<img width="921" alt="Screen Shot 2022-07-09 at 5 56 10 PM" src="https://user-images.githubusercontent.com/796815/178123880-16184f6c-4682-4c77-a979-f1f3c38f4961.png">

**Comment by zkhalapyan** [comment]
So far, prefixing it with `WalletConnectSwift` seems to have removed the problem,

```
func didSettle(session: WalletConnectSwift.Session){}
```

**Comment by llbartekll** [comment]
same here, it is not very recent

**Comment by zkhalapyan** [comment]
Yeh, was using older version, see https://github.com/WalletConnect/WalletConnectSwiftV2/issues/321.

Once V2 is functional, would be nice to add deprecation notice on these objects.
