### ISSUE TITLE
WalletConnectSwiftV2 swift package not correctly published

### ISSUE THREAD

**Issue by zkhalapyan** [WalletConnect/WalletConnectSwiftV2#329]
**Describe the bug**

Trying to get the hello world project out to test out WalletConnectSwiftV2; can't import the `WalletConnectSign` object in order to use `Sign` [as in the example here](https://docs.walletconnect.com/2.0/swift/sign/wallet-usage). 

**SDK Version**
 - Client: Swift 
 - Version: 5

**To Reproduce**
1. Add WalletConnectSwiftV2 as a dependency to a Swift/Xcode/iOS project [following instructions here](https://docs.walletconnect.com/2.0/swift/sign/installation).
2. Type `import WalletConnectSign`
3. Notice that you get an error `No such module as "WalletConnectSign"`

**Expected behavior**
Following the example app to import [WalletConnectSign](https://github.com/WalletConnect/WalletConnectSwiftV2/blob/main/Example/ExampleApp/SceneDelegate.swift#L2). 

**Screenshots**

<img width="690" alt="Screen Shot 2022-07-12 at 10 23 09 AM" src="https://user-images.githubusercontent.com/796815/178513165-5d7b5fa7-a9ad-4946-a9dc-3aa77fad5668.png">
our problem.

**Additional context**
On main branch!

**Comment by zkhalapyan** [comment]
I have been pulling the package off the main branch; via File -> Add Package 

For some odd reason, it's pulling in from https://github.com/WalletConnect-Labs/WalletConnectSwiftV2!

**Comment by zkhalapyan** [comment]
Like adding the package `https://github.com/WalletConnect/WalletConnectSwiftV2` from Xcode, is bringing in the archived GitHub repo! 🤷‍♂️

<img width="1237" alt="Screen Shot 2022-07-12 at 12 21 03 PM" src="https://user-images.githubusercontent.com/796815/178543214-e1a21718-9f06-42b2-ba4a-a92aafc3dba8.png">

**Comment by zkhalapyan** [comment]
Ah, I see what's happening: if you add `https://github.com/WalletConnect/WalletConnectSwiftV2` to Xcode's package search, it will bring up the older library called `WalletConnectSwiftV2` 🤦‍♂️

<img width="1122" alt="Screen Shot 2022-07-12 at 12 22 26 PM" src="https://user-images.githubusercontent.com/796815/178543463-382f97b2-15f0-42fc-9d94-85fc99602357.png">

**Comment by llbartekll** [comment]
![Screenshot 2022-07-12 at 18 54 30](https://user-images.githubusercontent.com/25840476/178549407-075e2701-cd3b-40a5-beb7-f9e98e45de7d.png)
you are using `WalletConncet-labs/` repo, it is not this one

**Comment by zkhalapyan** [comment]
@llbartekll my best guess is that the library not correctly published; both of the results below are not the correct ones lol one is old the other one is named correctly, but archived, this is quite confusing. I would take the following actions:

1. Publish the correct `WalletConnectSwiftV2` (this repo)
2. Kill the archived/old package called `WalletConnectSwiftV2` so that there is no confusion
3. Keep `WalletConnectSwift` which is pointing to V1 since there are probably some real users out there

I would verify that it works by searching for this repo's URL and making sure the correct WalletConnectSwiftV2 pops up.

<img width="1295" alt="Screen Shot 2022-07-12 at 3 33 59 PM" src="https://user-images.githubusercontent.com/796815/178580139-2292911d-02ea-4895-a3f2-470ae76868d5.png">

**Comment by llbartekll** [comment]
@zkhalapyan I think you may have some cache in xcode. 
1. double tap on the `WalletConnectSwiftV2` package
2. tap delete
3. paste `https://github.com/WalletConnect/WalletConnectSwiftV2` in search textfield 
4. this package will display so you can add it

**Comment by zkhalapyan** [comment]
That's correct, was caching the older version; deleting the cache, fetching with the new URL worked. Thank you!

**Comment by AndrewPetrov** [comment]
I have the same issue, but all links look fine. I chose all possible checkboxes to avoid mistakes when something important isn't imported.  I've cleaned the SPM cache, derived data, and project build folder, but still have a problem. 
![SCR-20230811-ops]
![SCR-20230811-oqi](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/37aa1ee7-97fe-4b4d-908b-6b9de3a4781b)
<img width="518" alt="image" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/87b35bf7-2100-4a79-9c70-361b9476b8d9">
(https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/09453e48-949e-4e23-914c-0fccb5891198)
![SCR-20230811-ov3](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13622708/9a91e5b2-55de-484b-959f-b48154a0f44d)
