### ISSUE TITLE
Is it possible delete Settled Pairings ?

### ISSUE THREAD

**Issue by lmcmz** [WalletConnect/WalletConnectSwiftV2#357]
While testing the demo app, I can see there are a lot of old existing in my cache. 
And it seems like there is no way for now in the SDK that we can delete those settled pairings.
It might be indeed if the wallet wanna reset itself to a fresh new state.

The duplicated pairing has been created when the same dapp and same wallet connect or reconnect multiple times.

![IMG_9186](https://user-images.githubusercontent.com/9669733/180500017-cab86f13-6849-4bd4-ac6e-2fd05b7aec0d.jpg)

**Comment by llbartekll** [comment]
hey @lmcmz for debugging purposes you can use `cleanup()` function. It will clean all the sdk's cache. But if you are developing a wallet you do not care too much about parings. You definitely do not need to list them to the user, you should present only sessions. Only Dapp should present pairings for the user in order to allow to propose sessions to the wallet without scanning qr code again.
And if you are concerned about about cached pairings on wallet that cannot be deleted, notice that inactive pairings expire after 30 days so they will be deleted automatically if not in use.

**Comment by lishuailibertine** [comment]
> hey @lmcmz for debugging purposes you can use `cleanup()` function. It will clean all the sdk's cache. But if you are developing a wallet you do not care too much about parings. You definitely do not need to list them to the user, you should present only sessions. Only Dapp should present pairings for the user in order to allow to propose sessions to the wallet without scanning qr code again. And if you are concerned about about cached pairings on wallet that cannot be deleted, notice that inactive pairings expire after 30 days so they will be deleted automatically if not in use.

I have the same problem, my understanding is that the SDK should not manage the validity period of the session, this should be handled by the wallet, for example: I have a page, its interaction logic is to scan the QR code every time the page is opened, the page When it disappears, the session needs to be closed.

**Comment by llbartekll** [comment]
hey @lishuailibertine, session and pairing are two different things. Sessions can be managed by the user/wallet and easily deleted or extended:
```
    public func extend(topic: String) async throws {
    public func disconnect(topic: String) async throws 
```
 Session's default life time is 7 days because we believe scanning qr code on every dapp visit is not a good UX.

**Comment by lishuailibertine** [comment]
> hey @lishuailibertine, session and pairing are two different things. Sessions can be managed by the user/wallet and easily deleted or extended:
> 
> ```
>     public func extend(topic: String) async throws {
>     public func disconnect(topic: String) async throws 
> ```
> 
> Session's default life time is 7 days because we believe scanning qr code on every dapp visit is not a good UX.

Ok, thanks for the reply, can pairings be deleted in release mode?

**Comment by lmcmz** [comment]
What if there is a malicious dapp which connected with the wallet before, then it's better for the wallet side we can delete the pairing on our end.

As well as, when the user sign out with different accounts, its better we can also cleanup the wallet connect cache in this scenario too.

**Comment by llbartekll** [comment]
@lmcmz good point,
keep track the issue at https://github.com/WalletConnect/WalletConnectSwiftV2/issues/447
we'll try to deliver it in the next release.
