### ISSUE TITLE
UI Tests are failing - universal linking

### ISSUE THREAD

**Issue by arein** [WalletConnect/WalletConnectSwiftV2#362]
**Describe the bug**
UI Tests are failing
https://github.com/WalletConnect/WalletConnectSwiftV2/blob/main/.github/actions/ci/action.yml#L51-L60

https://github.com/WalletConnect/WalletConnectSwiftV2/runs/7451525278?check_suite_focus=true#step:15:2980
(Scroll to the bottom of the ci step)
`Error: Process completed with exit code 65.`

**Expected behavior**
Tests dont' fail

<img width="644" alt="Screen Shot 2022-07-25 at 1 39 22 PM" src="https://user-images.githubusercontent.com/966091/180769609-b054ce69-c4a1-4549-8849-f72f1a90d2bc.png">

**Comment by llbartekll** [comment]
Cause of failing test is broken universal linking.
`apple-app-site-association` has been uploaded to new website but universal linking is still broken. 

`curl https://walletconnect.com/.well-known/apple-app-site-association`

**Comment by llbartekll** [comment]
`apple-app-site-association` has been fixed.
UI tests are passing.
