### ISSUE TITLE
Support `irn` instead of `iridium`

### ISSUE THREAD

**Issue by pedrouid** [WalletConnect/WalletConnectSwiftV2#364]
Related to https://github.com/WalletConnect/walletconnect-specs/issues/90

**Comment by llbartekll** [comment]
@MisterVants can we close this one? is it included in your last PR?

**Comment by flypaper0** [comment]
> @MisterVants can we close this one? is it included in your last PR?

there is implemented "inr" "iridium" wrappers, but "iridium" wrapper still in use

**Comment by MisterVants** [comment]
I'm replacing the calls
