### ISSUE TITLE
keyNotFound

### ISSUE THREAD

**Issue by lishuailibertine** [WalletConnect/WalletConnectSwiftV2#420]
**Describe the bug**
After the socket link succeeds, console Logs displays information about decode failures

**SDK Version**
 - Client: v0.9.3-rc.0
 - Version v0.9.3-rc.0

**To Reproduce**
1. Click on Scan QR code
2. After the socket connected , the log displays information about decode failures

**Screenshots**
![WX20220809-101719](https://user-images.githubusercontent.com/7145192/183549068-0298b213-5ca0-40d1-bda1-e72f763af19b.png)

**Device (please complete the following information):**
 - Device: iPhone7
 - OS: iOS15.0.2

**Comment by llbartekll** [comment]
hey, thanks for reporting, it's known issue and should be resolved soon but it does not affect behaviour of the sdk.
