### ISSUE TITLE
Update QR code URI with API prefix

### ISSUE THREAD

**Issue by MisterVants** [WalletConnect/WalletConnectSwiftV2#454]
### Description
Extend the WalletConnect URI implementation to include a prefix that specifies the target API. 
- The prefix needs to be queryable so the app can conditionally route the pairing URI to the correct API.
- For Auth URI, the prefix is `auth-`.
- To account for backward compatibility, the absence of the prefix should be equivalent to a `sign-` prefix.

### Example
`"wc:auth-7f6e504bfad60b485450578e05678ed3e8e8c4751d3c6160be17160d63ec90f9@2?relay-protocol=irn&symKey=587d5484ce2a2a6ee3ba1962fdd7e8588e06200c46823bd18fbd67def96ad303"`

**Comment by llbartekll** [comment]
irrelevant
