### ISSUE TITLE
App gets terminated because of unbalanced calls of beginBackgroundTask and endBackgroundTask

### ISSUE THREAD

**Issue by shmakovigor** [WalletConnect/WalletConnectSwiftV2#456]
**Describe the bug**
When the app goes to the background following console log appears. Background task named **Finish Network Tasks** comes from Wallet Connect lib. As a result, the app gets terminated in background by iOS, as stated in the log message.

**SDK Version**
Latest

**To Reproduce**
Run the app and move to the background.

**Console log**

> Background Task 3 ("Finish Network Tasks"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
> 
> Background task still not ended after expiration handlers were called: <_UIBackgroundTaskInfo: 0x2832d6d80>: taskID = 3, taskName = Finish Network Tasks, creationTime = 334273 (elapsed = 52). This app will likely be terminated by the system. Call UIApplication.endBackgroundTask(_:) to avoid this.

**Expected behavior**
Balanced calls of beginBackgroundTask and endBackgroundTask.

**Device (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 15.5

**Comment by llbartekll** [comment]
resolver in 0.10.0
