### ISSUE TITLE
Getting Started Tutorial - dapp integration

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/WalletConnectSwiftV2#52]

**Comment by zkhalapyan** [comment]
Any updates on this? There is no viable documentation source for dApp integration on iOS. I have been scavenging the web and trying to reverse engineer at this point.

**Comment by llbartekll** [comment]
@zkhalapyan did you took a look at our sample dapp?

**Comment by llbartekll** [comment]
https://docs.walletconnect.com/2.0/swift/sign/dapp-usage
