### ISSUE TITLE
Support client delegate with Combine

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/WalletConnectSwiftV2#55]
add combine api in order to allow to register multiple subscribers on client events.

**Comment by lourenco-marinho** [comment]
Hi @llbartekll, I hope you are doing well. I'd like to know if the project is open for contribution and if so, is there any other documentation on how this api should be designed?

Thanks :)

**Comment by llbartekll** [comment]
Hey @lourenco-marinho, yes we are open for contributions. In general the api should be a substitute for a WalletConnectClientDelegate and use `PassthroughSubjects`. If you'd like to contribute, please open PR to `develop` branch
