### ISSUE TITLE
how to run example wallet

### ISSUE THREAD

**Issue by smallerboy** [WalletConnect/WalletConnectSwiftV2#563]
when i try run, i always get miss package report

![image](https://user-images.githubusercontent.com/8731470/199280908-1421f714-0c85-40d8-97e7-18eefa3d1949.png)

mybe can give some guide,  

this one is not very novice friendly

**Comment by llbartekll** [comment]
hey, try to reset packages cache in xcode:
File->Packages->Reset Packages Cache

**Comment by smallerboy** [comment]
> hey, try to reset packages cache in xcode: File->Packages->Reset Packages Cache

thanks, i will try, mybe because my network

**Comment by smallerboy** [comment]
thanks every one
