### ISSUE TITLE
Can't import library when using another web3.swift library

### ISSUE THREAD

**Issue by DarthMike** [WalletConnect/WalletConnectSwiftV2#592]
**Describe the bug**
Setting up a project with the latest version, and another web3 provider library creates conflicts

**SDK Version**
 - Client: Xcode
 - Version 1.0.4, 1.05
 - 
**To Reproduce**
1. Create new project
2. Add https://github.com/argentlabs/web3.swift as dependency to project
3. Add WalletConnectSwiftV2 as dependency to project

**Expected behavior**
Should be able to add it

**Screenshots**
![Screenshot 2022-11-15 at 12 45 28](https://user-images.githubusercontent.com/1030987/201912060-895145c1-a82b-474b-b1d2-1c7ba4add04f.png)

```
error project: Failed to resolve dependencies Dependencies could not be resolved because root depends on 'web3.swift' 1.2.0.
'web3.swift' 1.0.0 is required because 'walletconnectswiftv2' 1.0.5 depends on 'web3.swift' 1.0.0 and root depends on 'walletconnectswiftv2' 1.0.5.
```
**Device (please complete the following information):**
N/A

**Additional context**
Conflict related to imported Web3.swift dependency. Is it really necessary to import such a big library to this SDK?

**Comment by jatinm11** [comment]
@DarthMike Found any solution for this ?

**Comment by DarthMike** [comment]
@jatinm11 I think the best solution would be to not expose the web3 library used as a dependency, given WalletConnect is multichain. But we need the project owners who really understand the implications to decide on this.

**Comment by DarthMike** [comment]
Thanks for the fix @flypaper0
