### ISSUE TITLE
Investigate keychain issue in mac applicaiton

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/WalletConnectSwiftV2#598]
https://github.com/orgs/WalletConnect/discussions/1597#discussioncomment-4188329

**Comment by flypaper0** [comment]
Initial research results:
https://github.com/orgs/WalletConnect/discussions/1597#discussioncomment-4351064

**Comment by llbartekll** [comment]
@flypaper0 so the issue is not in sdk but in app, correct?

**Comment by flypaper0** [comment]
@llbartekll right

> Awesome! Thank you so much! Now we will continue our work on integrating WalletConnectV2.
