### ISSUE TITLE
Disconnecting for load balancing reasons  4010

### ISSUE THREAD

**Issue by Lvykk** [WalletConnect/WalletConnectSwiftV2#608]
When the Starscream version is 4.0.4, after I use WebSocket to connect, after 300 seconds, the disconnection operation is triggered(disconnected("Disconnecting for load balancing reasons", 4010))

**Comment by chadyj** [comment]
hey @Lvykk we have the reconnection logic implemented and going to release the changes today, please upgrade your version to v1.0.6

**Comment by Lvykk** [comment]
> 嘿@Lvykk我们已经实现了重连逻辑，今天将发布更改，请将您的版本升级到 v1.0.6

This is really good news. It is a very bad thing for developers to implement their own judgment status code for reconnection. This is very easy to cause a bad experience for users
