### ISSUE TITLE
Add Auth to Showcase App to authenticate for Chat

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/WalletConnectSwiftV2#618]

**Comment by kingdutch001** [comment]
Hi, my app is not too big and does not have many dependencies.
I've deployed it on Vercel, however, it is really slow.
when i run "npm run build" & "npm run start" localy it runs way faster as i would expect.
I think i may have deployed it in a wrong way.
If anyone could help me i would really appreciate it.
Thanks (:
