### ISSUE TITLE
Starscream's version is too low

### ISSUE THREAD

**Issue by lvzhehappy** [WalletConnect/WalletConnectSwiftV2#622]
The version used by Starscream is 3.1.2 and the current version 4.0.4 is very different, causing the upgrade to encounter major obstacles，please change the WebSocketConnecting protocol，Make the upgrade go smoothly。thanks

**Comment by flypaper0** [comment]
@lvzhehappy did you faced any problems with implementing WebSocketConnecting for Starscream 4.0.4?

**Comment by lvzhehappy** [comment]
@flypaper0 yeah, Starscream 4.0.4 has changed more, didn't implementing WebSocketConnecting.We have re-updated the websocket in our projects,so that can compatible with WebSocketConnecting

**Comment by flypaper0** [comment]
Good to hear! We are recommend to use Starscream v3, because v4 had some issues when we tested it. But I believe it's also possible to implement WebSocketConnecting for v4 if you really need it

**Comment by kevinwo** [comment]
@lvzhehappy Would you mind sharing what you did to support compatibility with Starscream 4? I'm a bit stuck at the moment.

@flypaper0 Do you have any guidance as well? It looks like Starscream 4 has been out for two years now, with other projects like web3swift supporting it. Would love to see v4 or alternative support!

**Comment by lvzhehappy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lvzhehappy** [comment]
> 
customize starscream like this:
in Websocket file
    // MARK: - EngineDelegate
    public func didReceive(event: WebSocketEvent) {
        callbackQueue.async { [weak self] in
            guard let s = self else { return }
            s.delegate?.didReceive(event: event, client: s)
            s.onEvent?(event)
            
            //custom add ======================================
            switch event {
            case .connected:
                self?.mutex2.lock()
                self?.connected = true
                self?.mutex2.unlock()
                self?.onConnect?()
            case .disconnected:
                self?.mutex2.lock()
                self?.connected = false
                self?.mutex2.unlock()
                let error = WSError(type: .serverError, message: "Invalid HTTP server", code: 10000)
                self?.onDisconnect?(error)
            case .error(let error):
                self?.mutex2.lock()
                self?.connected = false
                self?.mutex2.unlock()
                self?.onDisconnect?(error)
            case .cancelled:
                self?.mutex2.lock()
                self?.connected = false
                self?.mutex2.unlock()
                self?.onDisconnect?(nil)
            case .text(let string):
                self?.onText?(string)
            case .ping:
                break
            case .pong:
                break
            case .reconnectSuggested:
                break
            case .binary, .viabilityChanged:
                break
            }
            //===================================================
        }
    }

**Comment by lvzhehappy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
