### ISSUE TITLE
Too narrow dependency version constraints in podspec

### ISSUE THREAD

**Issue by mrfripp** [WalletConnect/WalletConnectSwiftV2#631]
**Describe the bug**
The dependency WalletConnect/Web3.swift has the version constraint set to very old versions `SwiftCrypto` & `BigInt` when using CocoaPods which makes it very difficult to integrate into a project that already depends on those, as an example including both V1 & V2 while migrating. `WalletConnectSwiftV1` needs `SwiftCrypto ~>1.5` but `WalletConnectSwiftV2`  needs `SwiftCrypto ~> 1.0.0`

**SDK Version**
 - Client: Swift
 - Version: 1.0.5 using CocoaPods

**Expected behavior**
To have a more relaxed version constrain on like `WalletConnectSwiftV2 ~>1.0` which is "up to the next major version" which also matching the constraints in `Package.swift` when using SPM

See PR https://github.com/WalletConnect/Web3.swift/pull/3

**Comment by flypaper0** [comment]
Please check new cocoapods release (1.1.0). We removed Web3 dependency from package. I does not affect Sign SDK, but if you're interested in Auth more docs [here](https://github.com/WalletConnect/walletconnect-docs/blob/main/docs/swift/auth/signer-configuration.md)

**Comment by mrfripp** [comment]
Thanks that is an even better solution 👍
