### ISSUE TITLE
No callback received when disconnected

### ISSUE THREAD

**Issue by Lvykk** [WalletConnect/WalletConnectSwiftV2#632]
When I manually call Sign to disconnect, I find that there is no disconnect callback on my side. On the contrary, when I disconnect on the browser, all callbacks are normal.

**Comment by flypaper0** [comment]
"disconnect callback" are you talking about `sessionDeletePublisher`? If so `sessionDeletePublisher` will be called on another side after "disconnect" message will be delivered and handled

Disconnect is a async function and when async context is finished it means you're disconnected. No need to wait for callback
```swift
func someAsyncContext() async throws {
  try await client.disconnect(topic: topic)
  // here you are disconnected 
}
```

**Comment by Lvykk** [comment]
How can I know that I have been disconnected successfully? Can sessionRequestPublisherSubject call try await Sign.instance.disconnect(topic: topic) on the wallet side to send a signal?

**Comment by llbartekll** [comment]
>How can I know that I have been disconnected successfully? 

when the following function returns without throwing an error
 `try await client.disconnect(topic: topic)`

can you share what you want to achieve?

**Comment by Lvykk** [comment]
> > 我怎么知道我已经成功断开连接？
> 
> 当以下函数返回而没有抛出错误时 `try await client.disconnect(topic: topic)`
> 
> 你能分享你想要达到的目标吗？

Yes, there is no error, and the website also shows that the connection is disconnected normally, but all the codes I wrote in the sessionDeletePublisher method are not called. I think when I call try await client.disconnect(topic: topic) to disconnect , the code subscribed by sessionDeletePublisher should be called

**Comment by llbartekll** [comment]
just execute the same function on sessionDeletePublisher and when disconnect returns

**Comment by Lvykk** [comment]
> 只需在 sessionDeletePublisher 上执行相同的功能，当断开连接返回时

All my refresh page operations are placed in the subscription of sessionDeletePublisher, but unfortunately, when I call try await client.disconnect(topic: topic), sessionDeletePublisher does not receive any message

**Comment by flypaper0** [comment]
@Lvykk we adding sessionsPublisher in next release, does it solve your problem? https://github.com/WalletConnect/walletconnect-docs/pull/366
