### ISSUE TITLE
Investigate pairing metadata nil

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/WalletConnectSwiftV2#640]
```I'm try to get information about dApp metadata after approve(session). Session was settled, and it works normally, but peer field in pairing sill nil.```

**Comment by chadyj** [comment]
Comment from Discord:

> It's different behavior in Android and Ios. Both platform has AppUpdateMetadataService which updates pairing, when session_settled. But ios do it only when request coming (i think only dApp). So when android get all pairings it comes with right metadata(peer data)

**Comment by ealymbaev** [comment]
When can we expect this issue to be fixed?

**Comment by llbartekll** [comment]
https://github.com/WalletConnect/WalletConnectSwiftV2/pull/641

We will probably make a release this week.

**Comment by ant013** [comment]
Hi. #641 has some wrong behavior. You try to set metadata to pairing using session-topic.
for pairingRegisterer.updateMetadata(topic, metadata: session.peerParticipant.metadata) method just need to use payload.topic when settleRequest created.

Ex.

 Relay: Subscribing to topic: ab2d481c00b04b492d08cf5ccf604339dbd0312f1c5f2b751b179974fdb0f955
 Received Session Proposal

Payload topic: ab2d481c00b04b492d08cf5ccf604339dbd0312f1c5f2b751b179974fdb0f955
Session topic: 1bc243aa162c205784ec135623a4ad9b6b86c3d8886e356f0a915941c2123fec

Try to set metadata: AppMetadata(name: "", description: "", url: "https://react-app.walletconnect.com", icons: [], redirect: nil) to
topic: 1bc243aa162c205784ec135623a4ad9b6b86c3d8886e356f0a915941c2123fec 
All pairings:
pairing.topic = ab2d481c00b04b492d08cf5ccf604339dbd0312f1c5f2b751b179974fdb0f955

**Comment by ant013** [comment]
One more thing. 
ApproveEngine.swift
in line 84: you capture pairing struct from store. After update storage with metadata from settleRequest,
in line 98: pairingStore.setPairing(pairing) - you again save pairing without metadata.

Before update expirity of pairing, you need get it again. (About guard- you can just check if it's not nil, you don't use it for next code)

**Comment by flypaper0** [comment]
@ant013 thanks for reporting the bug. We updated PR, and also did a small refactoring
