### ISSUE TITLE
Spurious build warning message: "WalletConnectRelay/PackageConfig.json' of type 'text.json' for architecture 'arm64'"

### ISSUE THREAD

**Issue by hboon** [WalletConnect/WalletConnectSwiftV2#669]
This message:

> Build target WalletConnectSwiftV2
> 
> no rule to process file '<my project path>/Pods/WalletConnectSwiftV2/Sources/WalletConnectRelay/PackageConfig.json' of type 'text.json' for architecture 'arm64'

**Comment by flypaper0** [comment]
closed with https://github.com/WalletConnect/WalletConnectSwiftV2/pull/672
