### ISSUE TITLE
Session failing to send requests after 5-10 minutes

### ISSUE THREAD

**Issue by Jake-Mulhern** [WalletConnect/WalletConnectSwiftV2#699]
**Describe the bug**
I pair with the example dApp using my wallet application that I am building in React-Native.  If I use the send_transaction or personal_sign buttons and the request is sent to my application.  However, if I wait about 5-10 minutes and try to make a request nothing happens.  It appears the session is dying after 5-10 minutes and I receive no notification.  

**SDK Version**
 - Client: Javascript: @walletconnect/web3wallet
 - Version 1.0.0

**To Reproduce**
-Connect with example dApp using QR code
-Accept session proposal
-Use example dApp to send a personal_sign request
-accept or reject request
-wait about 5-10 minutes
-try another personal_sign request from example dApp
-observe that no request is sent to the wallet application

**Expected behavior**
The wallet app should still receive the request and be able to handle it.

**Screenshots**

**Device (please complete the following information):**
 - Device: iPhone 13 pro
 - OS: iOS 16.1.1
 - Browser: React-native
 - Version "0.69.6"

**Additional context**

The example dApp is (https://react-app.walletconnect.com/)

**Comment by Jake-Mulhern** [comment]
-Update to this:
The requests have stopped being sent even when I repeatedly send requests.  Basically session only seems to last for 5 minutes.

**Comment by flypaper0** [comment]
@Jake-Mulhern Could you create issue on https://github.com/WalletConnect/walletconnect-monorepo if problem still exist please
