### ISSUE TITLE
cocoapods   unavailable

### ISSUE THREAD

**Issue by smallerboy** [WalletConnect/WalletConnectSwiftV2#704]
when i used upgrade Guide with web3wallet, i  find pod unavailable
![image](https://user-images.githubusercontent.com/8731470/216926052-6e3d6935-5460-4da9-b323-17e568a3cc81.png)
![image](https://user-images.githubusercontent.com/8731470/216931494-e568a97e-bf53-4d6b-adf2-1810cea55868.png)

WalletConnectSwiftV2  pod last version  is 1.3.0, and it can not find web3wallet sub item

**Comment by flypaper0** [comment]
This could help
`  pod 'WalletConnectSwiftV2/Web3Wallet', '1.3.0'
`

**Comment by smallerboy** [comment]
thanks, i will try it later

**Comment by smallerboy** [comment]
> This could help ` pod 'WalletConnectSwiftV2/Web3Wallet', '1.3.0'`

it's work for us, thanks

**Comment by smallerboy** [comment]
it's work
