### ISSUE TITLE
'Session.Event' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by Crypto-Doby** [WalletConnect/WalletConnectSwiftV2#728]
- Client: Swift
 - Version 1.3.0

using cocoa pods and trying to create Session.Event instance, but got this error.
same as Session and Session.Proposal, but these two types do not needs to create manually. so it's fine ~

**Comment by llbartekll** [comment]
Session.Event has no public initialiser

**Comment by Crypto-Doby** [comment]
@llbartekll 
I want to emit an event to a dApp with this function in SignClient:
```
    /// For the wallet to emit an event to a dApp
    ///
    /// When a client wants to emit an event to its peer client (eg. chain changed or tx replaced)
    ///
    /// Should Error:
    /// - When the session topic is not found
    /// - When the event params are invalid
    /// - Parameters:
    ///   - topic: Session topic
    ///   - event: session event
    ///   - chainId: CAIP-2 chain
    public func emit(topic: String, event: Session.Event, chainId: Blockchain) async throws {
        try await sessionEngine.emit(topic: topic, event: event.internalRepresentation(), chainId: chainId)
    }
```
but don't know how to create the Event instance.

the dapp's supported Events is in the ProposalNamespace, but is in string format. how do I create or get the Session.Event?
 ```
public struct ProposalNamespace: Equatable, Codable {

    public let chains: Set<Blockchain>?
    public let methods: Set<String>
    public let events: Set<String>

    public init(chains: Set<Blockchain>? = nil, methods: Set<String>, events: Set<String>) {
        self.chains = chains
        self.methods = methods
        self.events = events
    }
}
```

**Comment by llbartekll** [comment]
hey @Crypto-Doby 
please upgrade the sdk to the lates version

and take a look at this test:
https://github.com/WalletConnect/WalletConnectSwiftV2/blob/2886a39933535969b3abb190729946057fecfd34/Example/IntegrationTests/Sign/SignClientTests.swift#L350

**Comment by Crypto-Doby** [comment]
thanks ~ I will go and take a look ~
