### ISSUE TITLE
Got error on webSocketNotConnected after scan an QR code

### ISSUE THREAD

**Issue by chenyoh** [WalletConnect/WalletConnectSwiftV2#733]
**Describe the bug**
For now, the example app is not working when scanning the QR code.

**SDK Version**
 - Client: [Swift]
 - Version [1.3.0]

**To Reproduce**
Go to https://react-app.walletconnect.com/
Click on connect
Open example wallet App
Scan the QR code
Error shown

**Expected behavior**
Wallet connect should establish the connection.

**Screenshots**
![截屏2023-02-24 17 47 0003](https://user-images.githubusercontent.com/19606566/221146843-214c2db1-c895-48b0-98a9-9c03432256a9.png)

**Device (please complete the following information):**
 - Device: [iPhone11 promax]
 - OS: [e.g 14.4]

**Additional context*
<img width="920" alt="截屏2023-02-24 17 51 0001" src="https://user-images.githubusercontent.com/19606566/221147983-3f20d95c-3dd6-4470-b994-11dcb59fe7b3.png">
* Do I need to turn on this switch before I can test it??

**Comment by alexander-lsvk** [comment]
Hi @chenyoh , you can try to enable sign v2, auth v1 and make sure that you've specified your project id:
`Networking.configure(projectId: *PROJECT_ID*, socketFactory: DefaultSocketFactory())`

**Comment by llbartekll** [comment]
@chenyoh were you able to establish a session?
can we close the issue?
