### ISSUE TITLE
The wallet connect URL generated does nothing when scanned

### ISSUE THREAD

**Issue by pranav-singhal** [WalletConnect/WalletConnectSwiftV2#753]
**Describe the bug**
I am trying to create a `wc://` url using the WalletConnectSwiftV2 SDK

This is the code that I am writing

```
            Networking.configure(projectId: "<my_project-Id>", socketFactory: DefaultSocketFactory())

            let methods: Set<String> = ["eth_sendTransaction", "personal_sign", "eth_signTypedData"];

            let namespaces: [String: ProposalNamespace] = [
                "eip155": ProposalNamespace(
                    chains: [
                        Blockchain("eip155:137")!
                    ],
                    methods: [
                        "eth_sendTransaction",
                        "personal_sign",
                        "eth_signTypedData"
                    ], events: []
                ),
                "eip155:1": ProposalNamespace(
                    methods: [
                        "eth_sendTransaction",
                        "personal_sign",
                        "eth_signTypedData"
                    ],
                    events: []
                )
            ]
            let sessionProperties: [String: String] = [
                "caip154-mandatory": "true"
            ]
           let uri = try await Pair.instance.create()
            try await Sign.instance.connect(requiredNamespaces: namespaces,sessionProperties: sessionProperties, topic: uri.topic)
```

For the socket factory, this is what I am doing

```
extension WebSocket: WebSocketConnecting { }


struct DefaultSocketFactory: WebSocketFactory {
    func create(with url: URL) -> WebSocketConnecting {
        return WebSocket(url: url)
    }
}
```

Once I have the uri, I try to scan the QR generated from `uri.absoluteString` - but nothing happens

I assume that I missed pasing something, but not sure what

**SDK Version**
 - Client: [e.g.  Swift]

**To Reproduce**
1. Run the above code

**Expected behavior**
The uri generated should be scannable by any walletConnect compatible wallet's scanner ( like MetaMask)

**Screenshots**

**Device (please complete the following information):**
 - Device: Iphone 14 Pro Max
 - OS: [e.g. iOS16.1]

**Comment by llbartekll** [comment]
hey @pranav-singhal did you generate a projectID fro your project?

**Comment by pranav-singhal** [comment]
Hey @llbartekll

 yes I did generate a project ID, I just removed it when uploading the code - snippet

quick update on this issue

As it turns out, the QR generated seems to work when scanned on TrustWallet ( IOS ) - but not when I scan it on Metamask ( IOS )

**Comment by pranav-singhal** [comment]
@llbartekll any update here?
Not sure why the generated link is not working with metamask

**Comment by llbartekll** [comment]
Metamask is still integrating the v2. 
But you can try with other wallets like Zerion or Spot too
