### ISSUE TITLE
add extend method to increase expiry (controller-only)

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/WalletConnectSwiftV2#8]
client should have a public `extend()` method that allows to increase sequence expiry time.
only controller should be allowed to perform this request.
by default session should be extended by 7 days and pairing by 30 days

 
- [x]  Add extend method to pairing engine for controllers
- [x]  Add extend method to session engine for controllers
- [x]  Handle incoming extension internally in the pairing engine
- [x]  Handle incoming extension internally in the session engine
- [x]  add didExtend(pairing:) delegate method  - non controller
- [x]  add didExtend(session:) delegate method  - non controller
- [x]  Add error message for invalid or unauthorized extension
- [x]  Test happy path of valid extend method being called
- [x]  Test error message when non-controller calls extend
- [x]  Test error message when ttl is higher than default
- [x]  Test error message when ttl is lower than current expiry

**Comment by llbartekll** [comment]
https://github.com/WalletConnect/walletconnect-monorepo/pull/717/files
