### ISSUE TITLE
get balance request fails

### ISSUE THREAD

**Issue by MohitTilwani15** [WalletConnect/WalletConnectSwiftV2#847]
**Describe the bug**

I am trying to connect to other wallets to get their addresses, account balances and any change in their balance.

User can connect to the wallet by the clicking the button which will redirect them to the wallet app where they can approve/reject the request

```
PrimayActionButton(
        text: "Connect",
        action: {
          Task {
            let methods: Set<String> = ["eth_sendTransaction", "eth_signTransaction", "eth_sign", "personal_sign", "eth_signTypedData"]
            let blockchains: Set<Blockchain> = [Blockchain("eip155:1")!]
            let namespaces: [String: ProposalNamespace] = [
              "eip155": ProposalNamespace(chains: blockchains, methods: methods, events: ["accountsChanged", "chainChanged"])
            ]
            let uri = try await Pair.instance.create()
            QRCodeString = uri.absoluteString
            try await Sign.instance.connect(requiredNamespaces: namespaces, topic: uri.topic)
            let url = URL(string: "https://argent.link/app/wc?uri=\(uri.absoluteString)")!
            await UIApplication.shared.open(url, options: [:])
          }
        }
      )
```

I am able to successfully redirect to the wallet app where I can see the modal which lists down all the possible things I am granting request for. But after I click on approve and go back to my app, I don't receive any response in the `sessionResponsePublisher` and sometimes I receive an error `JSONRPC.RPCResult.error(JSONRPC.JSONRPCError(code: 0, message: "", data: nil)))`

code where I make a request to ETH get balance which is throwing an error

```
Sign.instance.sessionSettlePublisher
      .receive(on: DispatchQueue.main)
      .sink { session in
      session.namespaces.values.forEach { namespace in
          namespace.accounts.forEach { account in
            let request = Request(
              topic: session.topic,
              method: "eth_getBalance",
              params: AnyCodable([account.address, "latest"]),
              chainId: Blockchain(account.blockchainIdentifier)!
            )

            Task {
              do {
                try await Sign.instance.request(params: request)
              } catch {
                print(error)
              }
            }
          }
        }
      }.store(in: &publishers)
```

It seems like `eth_getBalance` is not possible from wallet connect ios SDK

**SDK Version**
 - Client: Swift 5.8
 - Version - using the `main` branch

**Comment by llbartekll** [comment]
does the wallet handle `eth_getBalance` ?
probably it doesn't and that's why it's not responding
