### ISSUE TITLE
Open an error via this link rainbow://wc?uri=wc:a8d4b331c85fd6868994273f217f311a0fcc1b39638b8f4fe92bb7483c1381bf@2?symKey=f88482a371fb91e699f1cc93f02ab6ff3871c4b1d8c3b02570520168cd4e23d4&relay-protocol=irn

### ISSUE THREAD

**Issue by mnz12138** [WalletConnect/WalletConnectSwiftV2#855]
**Describe the bug**

**SDK Version**
 - Client: [e.g.  Swift]

**To Reproduce**

**Expected behavior**

**Screenshots**
![IMG_0013](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/13588391/49b9cd64-91de-4cc4-b3c1-072878c8ca26)

**Device (please complete the following information):**

**Additional context**

**Comment by mnz12138** [comment]
Why is it closed?

**Comment by llbartekll** [comment]
I have no idea what you are reporting and how to reproduce.
Can you fill out the bug description and provide more details?
