### ISSUE TITLE
 web3swift was resolved to 2.5.0，What do I do？

### ISSUE THREAD

**Issue by MasterYong** [WalletConnect/WalletConnectSwiftV2#9]
CocoaPods could not find compatible versions for pod "Starscream":
  In snapshot (Podfile.lock):
    Starscream (= 4.0.4, ~> 4.0.4)

  In Podfile:
    WalletConnectSwift was resolved to 1.6.0, which depends on
      Starscream (~> 3.1)

    web3swift was resolved to 2.5.0, which depends on
      Starscream (~> 4.0.4)

**Comment by llbartekll** [comment]
This repo contains WalletConnect v2 protocol implementation.
