### ISSUE TITLE
Add session settlement method

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/WalletConnectSwiftV2#90]

**Comment by ClaraBara22** [comment]
3MA4oq9YV4xjXNQjodoKazH3eiPNKwAtz9 BTC

0x91f0D377E525Ae405E458684c0919908e54488E1   Binance 

0x91f0D377E525Ae405E458684c0919908e54488E1  ETHER

For Unstoppable wallet 

This is my best shot, I am unable to attempt to attach the wallets. I know it's a pain, but this is it. I apologize

**Comment by llbartekll** [comment]
@MisterVants so I am taking this.
