### ISSUE TITLE
Sample app does not work as intended with Metamask and TrustWallet

### ISSUE THREAD

**Issue by bujake** [WalletConnect/WalletConnectSwiftV2#918]
**Describe the bug**
Testing the Example app from this repository, I found that connecting with TrustWallet and Metamask does not work. 

**SDK Version**
 - Client: WalletConnectSwiftV2
 - Version 1.6.8

**To Reproduce**
1. After putting a valid project id (works on Android), run the `DApp` target that is defined in the `Example` app of this repository.
2. Wait for the app to open on the device, then press `Connect`.
3. Select Metamask or TrustWallet from the modal.
4. The specified wallet opens (TrustWallet prompts the connection dialog, but then throws an error - see screenshots; Metamask doesn't even prompt the connection approval dialog)

**Expected behavior**
I am able to connect with both wallets and then trigger `eth_personalSign` or `eth_sendTransaction` methods with the account I connected with and to the wallet I'm connected to.

**Screenshots**
![image](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/137282162/8494abd0-c969-4f66-b493-f4c8828a96b8)
![image](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/137282162/6b46a7b5-69f3-49b5-8288-e0d32674b6bf)

**Device (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 16.5

**Additional context**
I tried removing Polygon and Sepolia chains -> TrustWallet connection works, but after trying to request the `eth_personalSign` method once, the rest of the methods that I subsequently try to execute do not work.

LE & off-topic: Please don't get suspicious that this is my first ever opened issue... I got my main account suspended without receiving a motivating email, trying to figure that out - I'm not a bot 😆 .

**Comment by AakifNadeem** [comment]
Facing the same issue. Did you find any workaround?

**Comment by flypaper0** [comment]
@bujake @AakifNadeem just want to confirm, issue solved?

**Comment by flypaper0** [comment]
I'm closing it for now
