### ISSUE TITLE
[w3i] w3i tab bar unread notification

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/WalletConnectSwiftV2#920]
**Is your feature request related to a problem? Please describe.**
Many apps show an unread badge indicator and count to let users know there are new or unread messages.

Adding it to the native part of the w3i integration is a hybrid approach that can combine the best of both approaches. 

**Describe the solution you'd like**

Add a badge and unread count to the w3i tab bar.

<img width="398" alt="Screenshot 2023-06-22 at 09 05 07" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/116099/09183c88-6ccd-4784-a306-df5e811d9b13">

**Additional context**
We expect this will be helpful for native developers for a deeper integration of w3i with imporved UX.

**Comment by flypaper0** [comment]
@chadyj as we do not have unread feature we can display badge with all messages count in our NotifySample app. Does It make sense?
