### ISSUE TITLE
400 Error - Bad Request When Registering iOS Device Token 

### ISSUE THREAD

**Issue by ngocpd-1250** [WalletConnect/WalletConnectSwiftV2#927]
**Describe the bug**
- Encountering a 400 error when calling Push.wallet.register(deviceToken: deviceToken) (WalletConnectSwiftV2)
<img width="950" alt="Screenshot 2023-06-24 at 15 40 26" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/49447154/315a5d6a-b471-4820-b8f0-1b0be41f0dfe">

**SDK Version**
 - Client: Swift
 - Version: 1.6.8

**To Reproduce**
- Calling Push.wallet.register(deviceToken: deviceToken) (WalletConnectSwiftV2)

**Expected behavior**
- Upon registering the device, the server should process the request successfully and return an appropriate response (e.g., 200 - OK) indicating a successful device registration.

**Comment by ngocpd-1250** [comment]
Unable to upload file p12
<img width="1123" alt="Screenshot 2023-06-25 at 10 04 27" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/49447154/e13b34ca-7eab-40d0-aa97-f5b3ef2ea481">

**Comment by llbartekll** [comment]
hey @ngocpd-1250 
what do you want to achieve? Do you want to receive Push notifications in your wallet on session requests? 
If so I would recommend to use different method and not depend on Push package.
if you are using Web3Wallet package already, call:
`Web3Wallet.instance.registerEchoClient(deviceToken: deviceToken)`

**Comment by ngocpd-1250** [comment]
thanks @llbartekll 
I'm still getting an error when trying to call `Web3Wallet.instance.registerEchoClient(deviceToken: deviceToken)`, using the Wallet code example from the repository.
<img width="426" alt="Screenshot 2023-07-02 at 19 41 56" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/49447154/2aa778a2-a6bb-436d-9de0-0561cb11327f">

**Comment by llbartekll** [comment]
Hey @ngocpd-1250 can you check now? It should be fixed

**Comment by ngocpd-1250** [comment]
@llbartekll Thank you very much. It's currently working.
