### ISSUE TITLE
Module without Web3Wallet

### ISSUE THREAD

**Issue by LomanLu** [WalletConnect/WalletConnectSwiftV2#928]
When I use Cocoapods to integrate into my project, I found that the submodule of Web3Wallet is missing, the version is the latest from 1.6.8

![1687747255483](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/90185858/389e7d20-fa63-4bc5-814c-219cb3a9bb46)
![1687747221628](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/90185858/c413b1f4-1289-4246-99e0-25a247b3cf58)

**Comment by ngn999** [comment]
There is no Web3Modal module.

**Comment by flypaper0** [comment]
Web3Wallet is a cocoapods subscpec right now. By default with `pod 'WalletConnectSwiftV2'` is installing WalletConnectSign. 

We're decided to install Web3Wallet by default, so I could recommend to use `pod 'WalletConnectSwiftV2/Web3Wallet'` until we'll draft new release with fix

**Comment by LomanLu** [comment]
> 

Thank you very much for your answer, using pod 'WalletConnectSwiftV2/Web3Wallet' has successfully solved this problem
