### ISSUE TITLE
webSocketNotConnected

### ISSUE THREAD

**Issue by cao13646** [WalletConnect/WalletConnectSwiftV2#933]
- WalletConnect 1.6.10
- Starscream 3.1.2

 DApp WebSocket Always webSocketNotConnected

**Comment by llbartekll** [comment]
add PROJECT_ID to the configuration file

**Comment by cao13646** [comment]
Already added

**Comment by cao13646** [comment]
https://github.com/WalletConnect/WalletConnectSwiftV2/issues/739
can connect, but not support iOS 14

**Comment by lilyDong** [comment]
got the same error
SDK version: 1.6.11
Starscream 4.0.4.2

**Comment by llbartekll** [comment]
@lilyDong are you connecting from China?

**Comment by lilyDong** [comment]
> @lilyDong are you connecting from China?

Yes. And I use relay.walletconnect.org , not  relay.walletconnect.com. When I don't use any vpn, it's ok. But there will be an error "webSocketNotConnected" when I use vpn. For our app, some logic needs vpn.

**Comment by lilyDong** [comment]
SDK version 1.6.14. I can't connect websocket when I am in China without any VPN, but can connect when I use VPN.
