### ISSUE TITLE
Unable to connect Trust wallet with Fantom wallet via WalletConnect

### ISSUE THREAD

**Issue by RabbitHole26** [WalletConnect/WalletConnectSwiftV2#940]
**Describe the bug**

I've established a connection between the Trust wallet and Fantom wallet via WalletConnect. The connection is listed in the WalletConnect settings in the Trust wallet on my iOS device. However, I am unable to access Fantom wallet, and when I try to establish a new connection I get a "failed to connect error" message. I tried to do this by accessing Fantom wallet on my desktop device and mobile device via the browser.

I've reached out to Fantom wallet support on Discord and they redirected me here after providing this explanation:

"team have tested the PWA wallet on Trust Wallet a imToken wallets to confirm it works ok, maybe you can try that path as well? 

the v.1 and v.2 are incompatible, so there is a possibility that the connecting app does not support v.2 connection protocols yet.
Our experience with the v.2 testing is that the new Wallet Connect systems seems to be overloaded from time to time causing the wallet to take up to a few minutes to get a confirmation of the connection. Unfortunately, this is an issue on the Wallet Connect side, not our."

There are two Fantom wallets versions at the moment:

old wallet: https://fwallet.fantom.network

new wallet: https://wallet.fantom.network

I can't connect to either wallet via WalletConnect (failed to connect error). All of my funds are stuck in the Fatom wallet which I cannot access. I am a non-tech individual and it is very difficult for me to understand how these things work and what should be done next. I also don't fully understand the Fantom support reply, I've asked for clarification in a lay language (non-tech) but haven't heard yet.

**SDK Version**
 - Client: [e.g.  Swift]

I have no idea where to find the information requested in this section.

**To Reproduce**

1. Go to

https://fwallet.fantom.network

and

https://wallet.fantom.network

2. Click on the WalletConnect button on the website.

3. Open Trust wallet, go to Settings -> WalletConnect -> New connection.

4. Scan the QR code shown on the website.

5. The WalletConnect feature in the Trust wallet displays the message "Connecting may take a few seconds".

6. After some time (approx. 20 seconds), I see the message "Connection failed".

Here is a video: 

https://github.com/WalletConnect/WalletConnectSwiftV2/assets/138439310/c65636ec-4dbb-4fb8-885b-dfe071721eca

**Expected behavior**
I am able to access my Fantom wallet via the Trust wallet by using WalletConnect

**Device (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.5.1
 - Browser on a desktop PC: Brave [Version 1.52.129 Chromium: 114.0.5735.198 (Official Build) (64-bit)](https://brave.com/latest/)
 - Browser on a mobile device: Brave [Verson 1.51.2]
 - Trust wallet version 8.9

**Additional context**
I've tried the following:

- disabling VPN
- tried the newest versions of other browsers: Firefox, Chrome, Safari
- restarted the iOS device
- cleared cache/cookies in the browsers

Things I thought about but haven't tried:

- removing the existing connection between the Fantom wallet and Trust wallet in the WalletConnect settings in the Trust wallet

I was afraid to do this as I am not sure what the consequences might be, and I wanted to have some evidence that the connection was established in the first place.

**Comment by llbartekll** [comment]
@alexander-lsvk

**Comment by DRFUGHESIUGHIUOSERG** [comment]
I've imported my trust wallet into metamask and connected to old fantom wallet this way. Also, I've tried the PWA fantom wallet with wallet connect but it didn't work as well.

**Comment by RabbitHole26** [comment]
Frankly, I am not sure I just stopped connecting to this wallet via WalletConnect.
