### ISSUE TITLE
Not found - DNS TXT verification record not found

### ISSUE THREAD

**Issue by chenyoh** [WalletConnect/WalletConnectSwiftV2#945]
**Describe the bug**
I keep getting 'not-found - DNS TXT verification record not found.' I have added this TXT to our domain name 'https://onto.app/' when verifying urls on Wallet Connect And 72 hours have passed

In addition, I would like to ask another question: When I used Xcode to debug the Demo provided by you, the projectId in the Demo has been changed to those applied by me, but the prompt of 'websocketnotconnect' has been displayed all the time. Do I need to verify the url before I can use the SDK?

[https://user-images.githubusercontent.com/19606566/221146843-214c2db1-c895-48b0-98a9-9c03432256a9.png](example)

**SDK Version**
 - Client: Swift
 - Version 1.6.0

**Comment by llbartekll** [comment]
hey @chenyoh do you connect from China?

**Comment by LeoTnT** [comment]
![WX20230707-094840@2x](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/14950154/cfb33a04-3821-4b37-9ae2-ef61b9baa300)
hope i can help you~
