### ISSUE TITLE
Several issues when I install the walletconnectv2 dependency into the new project

### ISSUE THREAD

**Issue by nick70007** [WalletConnect/WalletConnectSwiftV2#953]
I have created a new Xcode project with version 15.2. When I install WalletConnectV2 dependency into the project and then build the code, then I get several issues. Can someone provide me the solution and also probably a demo on connecting to metamask in ios swift. I am also having this issue "Type 'SignClient' does not conform to protocol 'SignClientProtocol'". Also I have integrated the package with SPM and it gives me so much error. But the same thing I install with Cocoapods, it doesnt give me error. In the latter case how would i access WalletConnectModal. I dont how do i integrate this in ios swift project. Version 1 was easy to understand. Basically I want to connect to the metamask, sign the transaction, return to the dapp

**Comment by llbartekll** [comment]
>"Type 'SignClient' does not conform to protocol 'SignClientProtocol'"
you are not suppose to init SignClient, take a look at out dapp usage docs
https://docs.walletconnect.com/2.0/api/sign/dapp-usage?platform=ios

**Comment by flypaper0** [comment]
@nick70007 WalletApp in our code is more relevant integration example now
