### ISSUE TITLE
Tag 6.6.6 causes confusion

### ISSUE THREAD

**Issue by bisgardo** [WalletConnect/WalletConnectSwiftV2#975]
**Describe the bug**

Tag `6.6.6` exists, but there are newer releases with lower version numbers.

When adding the library as a dependency, you're given this older version by default; see screenshot below.

You need to go dig out the version range in this repo to add the dependency properly. This is undocumented, unexpected, and involves guessing.

**SDK Version**
N/A

**To Reproduce**
Add the package https://github.com/WalletConnect/WalletConnectSwiftV2 as a dependency in Xcode.

**Expected behavior**
You get the newest release by default.

**Screenshots**
<img width="1088" alt="image" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/205161/4abc62b2-3957-4b54-95f8-7a8899246f32">

**Device (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by flypaper0** [comment]
May be was created for some debug purposes. deleted
