### ISSUE TITLE
[Sign] Connection doesn't provide session after confirm connection on the Wallet app

### ISSUE THREAD

**Issue by nicolascabaret** [WalletConnect/WalletConnectSwiftV2#981]
**Describe the bug**
When a connection request is sent by our dApp, the request is well received by the Wallet but the confirmation click on the popup doesn't send any usable session back to our dApp.

I tried with 3 different wallets (MetaMask, Trust Wallet and Rainbow) and they both behave the same way. 

Technically speaking, it seems the `Sign.instance.sessionSettlePublisher` doesn't publish anything. Here is the simple subscribe we made on:
```
Sign.instance
     .sessionSettlePublisher
     .receive(on: DispatchQueue.main)
     .sink { [weak self] session in
          self?.session = session
          self?._walletAddresses.send(session.accounts.map { $0.address })
      }
.store(in: &storage)
```

All publishers of `Sign.instance` are registered right before calling `Sign.instance.connect()`. 
Here are following namespaces we use:
```
let namespaces = [
     "eip155": ProposalNamespace(
          chains: [Blockchain("eip155:1")!],
          methods: ["personal_sign"],
          events: []
     )
]
try await Sign.instance.connect(
     requiredNamespaces: namespaces,
     optionalNamespaces: namespaces,
     topic: uri.topic
)
```

⚠️ optionalNamespaces must be specified to be redirected to the initial dApp (seems to be another bug)

**SDK Version**
 - Client: Swift
 - Version 1.16.13

**To Reproduce**
1. Send a connect request from a dApp to a Wallet
2. Confirm the request on the Wallet
3. Wallet deeplink back to the dApp
4. No session nor event are published in dedicated Publishers

**Expected behavior**
`Sign.instance` publishers should correctly send events and session must be received

**Additional context**
We recently moved from WalletConnectV1 to V2 SDK and everything worked perfectly with V1

**Comment by flypaper0** [comment]
The problem could be because optional namespaces the same as required. Try to not provide optional namespaces by setting nil

**Comment by nicolascabaret** [comment]
Thanks for answering. Unfortunately, I already tried this before posting and it didn't change the behavior.

**Comment by siavkuong** [comment]
I'm facing the same issue with my application and Metamask.
Please have a look.

**Comment by reaperdtme** [comment]
Same issue here using WalletConnectModal

**Comment by sxiaojian88** [comment]
Same issue here using WalletConnectModal and Metamask

**Comment by arturzainulov** [comment]
Same issue here using WalletConnect
Who solved this issue?

**Comment by sxiaojian88** [comment]
Use this code can receive sessionSettlePublisher.
-  use WalletConnectModal,
- optionalNamespaces need a value.
- subscribe WalletConnectModal.instance.sessionSettlePublisher
But I can't send a sign request to metaMask, maybe It's another bug.



        let methods: Set<String> = ["eth_sendTransaction", "personal_sign", "eth_signTypedData"]
        let events: Set<String> = ["chainChanged", "accountsChanged"]
        let blockchains: Set<Blockchain> = [Blockchain("eip155:1")!]
        let namespaces: [String: ProposalNamespace] = [
            "eip155": ProposalNamespace(
                chains: blockchains,
                methods: methods,
                events: events
            )
        ]

        let defaultSessionParams =  SessionParams(
                                        requiredNamespaces: namespaces,
                                        optionalNamespaces: namespaces,
                                        sessionProperties: nil
                                    )
        WalletConnectModal.configure(
            projectId: "xxx",
            metadata: metadata,
            sessionParams: defaultSessionParams
        )

**Comment by PetecOvod** [comment]
Same issue. ETA for fix?

**Comment by willis-tagheuer** [comment]
Dear WalletConnect team, did you get a chance to take a look at this issue ?

**Comment by PetecOvod** [comment]
ETA?

**Comment by tomav** [comment]
Hi @alexander-lsvk (and maybe @flypaper0), following your inputs in #996, please find more information using today's git version of your ExampleApp:
* using Rainbow, detected as installed, v1.9.5 (12), by restarting the app I can see the session (good to know, thanks for that)
* using Metamask, detected as installed, v7.8.0 (1174), when redirected to the wallet, the "connect" button does not even appear
``` [SignClient.swift]: Connecting Application - connect(requiredNamespaces:optionalNamespaces:sessionProperties:topic:) - line: 215 - 2023-10-11 00:36:44
 [AppProposeService.swift]: Propose Session on topic: ee76d07803b9d6496b09e1f471116ad7155c688231e8788577c74d07abc732ea - propose(pairingTopic:namespaces:optionalNamespaces:sessionProperties:relay:) - line: 28 - 2023-10-11 00:36:44
RPCRequest
{"id":1696977404497484,"jsonrpc":"2.0","error":{"message":"Unsupported namespace key.","code":5104}}
RPCResponse
 [ApproveEngine.swift]: Session Proposal has been rejected - handleSessionProposeResponseError(payload:) - line: 264 - 2023-10-11 00:36:54
Reason(code: 5104, message: "Unsupported namespace key.")
 [SignClient.swift]: Connecting Application - connect(requiredNamespaces:optionalNamespaces:sessionProperties:topic:) - line: 215 - 2023-10-11 00:36:54
 [AppProposeService.swift]: Propose Session on topic: 1e90c2bf86b77c771a8e6ffc1937104bcf748204fb14e69830beafa17d8a87c4 - propose(pairingTopic:namespaces:optionalNamespaces:sessionProperties:relay:) - line: 28 - 2023-10-11 00:36:54
```

* using Ledger Live, not detected as installed, v3.30.0 (17), I have a "no valid link for opening given wall found" displayed when clicking Ledger logo. When using "Try Again" button, I end up on walletconnect.com with error "Application error: a client-side exception has occurred"

```
[SignClient.swift]: Connecting Application - connect(requiredNamespaces:optionalNamespaces:sessionProperties:topic:) - line: 215 - 2023-10-11 00:38:22
[AppProposeService.swift]: Propose Session on topic: 3d51590a88fa4bc4fb66409ff16a3a6abd6ac81693ac47d77b626a9dcdd486c5 - propose(pairingTopic:namespaces:optionalNamespaces:sessionProperties:relay:) - line: 28 - 2023-10-11 00:38:22
2023-10-11 00:38:36.211983+0200 DApp[1209:93187] [Snapshotting] Snapshotting a view (0x118814600, UIKeyboardImpl) that is not in a visible window requires afterScreenUpdates:YES.
```
Like @nicolascabaret, we used WalletConnect v1 with Metamask and Ledger without any issue (we use mainly `personal_sign`)
We'd love to know continue providing innovative web3 features to our clients.
Let us know how we can move forward.

Thanks!

**Comment by flypaper0** [comment]
WalletConnectModal is deprecated now. Try to use Web3Modal or custom implementation with Web3Wallet
