### ISSUE TITLE
[Router] Fix WalletConnectRouter for iOS 17

### ISSUE THREAD

**Issue by flypaper0** [WalletConnect/WalletConnectSwiftV2#988]
**Describe the bug**
"Hi, for info WalletConnectRouter does not seem to work in iOS 17.
Side note, I saw you are using private iOS APIs to go back to the previous app (ie access to _systemNavigationAction) so it might be dangerous to push such code in production.
You might have to test this yourself on iOS 17 but I’m quite sure this has been patched, as it is not working with GBoard dictation anymore (they were using the same “trick” as you do with their keyboard extension, but Apple were not too observant on this maybe as it is Google…)"

**Comment by alexanderkhitev** [comment]
Hey! Any news/updates?

**Comment by ldkfreetoplay** [comment]
iOS 17 has been released and I'm having this issue now, is there a solution?

**Comment by riwa0803** [comment]
any updates?

**Comment by mluisbrown** [comment]
@alexanderkhitev can you explain how using Starscream fixes this issue with WalletConnect, which seems unrelated to web sockets? btw you said you use 3.1.2, but that version doesn't even seem to exist.

**Comment by mluisbrown** [comment]
> You might have to test this yourself on iOS 17 but I’m quite sure this has been patched

You are right @flypaper0, see [here](https://stackoverflow.com/questions/42516357/how-does-googles-custom-ios-keyboard-gboard-programmatically-dismiss-the-fron#comment135750489_68973387):

> object_getIvar now returns `nil`.

**Comment by simonmcl** [comment]
I saw the note about private API usage, is this true? I'm hoping to release in a few weeks (beta test going well), will my app get rejected for including WC2 due to this API usage? Is this going to be pulled out soon?

**Comment by flypaper0** [comment]
Right now the recommended way to solve that problem is providing `redirect` property for AppMetadata object. Redirect back to dapp should be done manually by wallets if `redirect` property is provided
