### ISSUE TITLE
NSURLErrorDomain Code=-1011 on iOS 17 beta 5. 

### ISSUE THREAD

**Issue by alexanderkhitev** [WalletConnect/WalletConnectSwiftV2#990]
**Describe the bug**
Hey guys! We use WalletConnect for our app and app is support from iOS 16. We've implemented `WalletConnectSocket` class that supports `WalletConnect's` `WebSocketConnecting` protocol and it works great on iOS 16. Now we start test the app on iOS 17 beta 5 and when we try to connect any wallet (for example Rainbow) as before we get **NSURLErrorDomain Code=-1011 \"There was a bad response from the server.\** but we didn't change any code related to the `WalletConnectSocket` class and also it continues work good on iOS 16. Any help/advice? Thanks!

**SDK Version**
 - Client: Swift
 - Version 1.6.14

**Comment by alexanderkhitev** [comment]
Hey guys, any updates/news?

**Comment by alexanderkhitev** [comment]
> > @alexanderkhitev do you use your custom socket client right?
> > If yes I could advise you few things:
> > 
> > 1. Decode JWT token `RelayURLFactory.swift` -> `line 26`, and check whether a domain is correct
> > 2. Try to use Starscream just for testing purposes to realize whether the problem is with your socket client implementation.
> 
> Hey @alexander-lsvk !
> 
> 1. I'll try
> 2. I tested it with Starscream latest version and it doesn't work and tested with 3.1.2 version like in the demo app, and it works at 90 % of cases.

@alexander-lsvk I checked. it's correct. 

{
  "sub": "00271bd5533f9841ba53c2932034b0957bfbd7ae7b5d1d04e41**1ebbdd565",
  "aud": "wss://relay.walletconnect.com",
  "iss": "did:key:*****",
  "exp": 1694003525,
  "iat": 1693917125
}

**Comment by flypaper0** [comment]
@alexanderkhitev sorry for long reply, issue still exists?
